kapitan/cli.py
kapitan/targets.py

this fixes a bug that overwrites the output_path if it is set to '.'

introduced compile_path, fixed output_path

---

kapitan/targets.py
kapitan/utils.py

roughly 30% faster than jsonnet `std.prune()`

faster prune function in python

---

README.md
kapitan/cli.py
kapitan/targets.py

This PR adds selective target compilation `compile -t <target>`, and removes support for `target.[json/yml]` files.

Selective compilation of targets

---

kapitan/version.py
setup.py

Tested new versions, works ok.

Updated Jinja2, jsonschema. Increment kapitan version.

---

requirements.txt

More info on
https://github.com/google/jsonnet/releases/tag/v0.10.0

Upgrade jsonnet dependency to latest (0.10.0)

---

kapitan/utils.py

Created jinja2 yaml filter

---

examples/kubernetes/scripts/apply.sh
examples/kubernetes/scripts/delete.sh
examples/kubernetes/scripts/kubectl.sh
examples/kubernetes/scripts/minikube/install_minikube.sh
examples/kubernetes/scripts/minikube/start_minikube.sh
examples/kubernetes/scripts/setup_cluster.sh
examples/kubernetes/scripts/setup_context.sh
kapitan/__init__.py
kapitan/__main__.py
kapitan/cli.py
kapitan/errors.py
kapitan/resources.py
kapitan/secrets.py
kapitan/targets.py
kapitan/utils.py
kapitan/version.py
setup.py
tests/__init__.py
tests/test_inventory.py
tests/test_jinja2.py
tests/test_jsonnet.py
tests/test_secrets.py

Updates copyright year in all files.

Updated copyright

---

kapitan/utils.py

Fixed searchvar bug. Optimised utils.deep_get function.

---

kapitan/cli.py
kapitan/utils.py
kapitan/version.py

Feature implementation for #41 
To be merged after PR #42

Added --pattern feature to inventory cli

---

README.md

Using delegated Docker volume mount configuration

---

kapitan/targets.py

Uses pool.imap_unordered() which improves performance ~10%
Correctly catches exceptions from compile_target(), logging failed target and terminating compile pool.
Fixes #62

Improved target compiling errors

---

kapitan/secrets.py

Addresses https://github.com/deepmind/kapitan/issues/55
- `lookup_fingerprints` returns a sorted list with removed duplicates.

Keeping 'secrets --write' and 'secrets --update-targets' consitent

---

kapitan/secrets.py

Opening file just before writing secret

---

kapitan/utils.py

Allows jinja2 expressions like
```
{% set defined_metrics = [] %}
{% for metric in metrics if metric not in defined_metrics %}
// logic
{% do defined_metrics.append(metric) %}
{% endfor %}
```

Added jinja2 'do' extension

---

kapitan/targets.py

https://github.com/esnme/ultrajson#encoder-options

add ujson escape_forward_slashes and remove sort_keys (it doesn't support it)

---

examples/terraform/README.md

Hi! Thanks for maintaining an awesome project :+1:
I just realized that kapitan supports terraform, but wasn't quite sure how I could actually use it.
I even didn't know that `*.tf.json` files are consumable by Terraform without any option, that was the hardest part for me to catch 😆
Anyway, I wrote up this to help future kapitan+terraform users not to get confused like me.

README for the terraform example

---

ci/Dockerfile

This will be used to create scripts to verify jsonnet formatting using `jsonnet fmt`

Add cjsonnet binary into the CI image

---

README.md
examples/kubernetes/compiled/minikube-es-2/manifests/es-discovery-svc.yml
examples/kubernetes/compiled/minikube-es-2/manifests/es-elasticsearch-svc.yml
examples/kubernetes/compiled/minikube-es/manifests/es-discovery-svc.yml
examples/kubernetes/compiled/minikube-es/manifests/es-elasticsearch-svc.yml
examples/kubernetes/compiled/minikube-mysql/manifests/mysql_secret.yml
examples/kubernetes/components/mysql/secret.jsonnet
examples/kubernetes/lib/kube.libjsonnet
tests/test_compile.py
tests/test_kubernetes_compiled/minikube-es-2/manifests/es-discovery-svc.yml
tests/test_kubernetes_compiled/minikube-es-2/manifests/es-elasticsearch-svc.yml
tests/test_kubernetes_compiled/minikube-es/manifests/es-discovery-svc.yml
tests/test_kubernetes_compiled/minikube-es/manifests/es-elasticsearch-svc.yml
tests/test_kubernetes_compiled/minikube-mysql/manifests/mysql_secret.yml

- Updated kube.libjsonnet in example
- Recompiled
- Fixed tests
- Some typos

Update kube libsonnet

---

kapitan/utils.py

- Added support for globbing on any level in the search (it only worked on last element before):
```
kapitan searchvar parameters.elastic*.replicas
OR
kapitan inventory -t minikube-es -p parameters.elastic*.replicas
```
- Now respects the variable chain
Fixes #107

Fixed deep_get recursion and search

---

kapitan/targets.py
kapitan/utils.py

Slight improvement in compilation speed and `searchvar` or `inventory -p <search>`

Improve caching

---

README.md
kapitan/secrets.py

Derives an RSA public key from a private key. Usage:
```
private_key: ?{gpg:targets/${target_name}/private_key|rsa}
public_key: ?{gpg:targets/${target_name}/public_key|rsapublic:targets/${target_name}/private_key}
```

Added rsapublic function to gpg backend

---

kapitan/utils.py

Better kapitan version checking

---

kapitan/cli.py
kapitan/refs/secrets/gpg.py

Secrets fixes

---

.travis.yml
Dockerfile
requirements.txt

- Bumped travis and docker to python 3.7
- Reduced the kapitan docker image size by half
- Updated cryptography and requests

Travis, Docker and requirements updates

---

kapitan/cli.py
kapitan/refs/base.py
kapitan/refs/secrets/gkms.py
kapitan/refs/secrets/gpg.py

- Moved `search_target_token_paths` to refs/base.py as it's not gpg specific
- Implemented update and validate for gkms secrets
- Fixes #150

gkms update and validate secrets

---

docs/pyenv-scl.md

A few nitpicks to apply some polish.  I added a missing closing parenthesis and changed 'Fedora release' to 'Fedora project'
Also added some dollar signs to the start of commands to indicate that they're shell commands and that they should be run as a non-privileged user.  Commands that need to be run as root have hash signs at the start of the line.

Missed a closing parenthesis, other minor nitpicks

---

.travis.yml
ci/Dockerfile
requirements.txt

jsonnet changelog here:
https://github.com/google/jsonnet/releases/tag/v0.12.0

Upgrade jsonnet

---

kapitan/refs/secrets/gpg.py

Fix #161: Problem was key['expires'] was just an empty string when set to infinite.

Fix #161: gpg write fails when expires is set to 0 (infinite).

---

CHANGELOG.md

Consolidated updates from rc editions for clarity.

Start release deepmind/release-v0.22.0

---

MANIFEST.in
README.md
kapitan/cli.py
kapitan/initialiser.py
kapitan/inputs/templates/components/my_component/my_component.jsonnet
kapitan/inputs/templates/components/other_component/__init__.py
kapitan/inputs/templates/inventory/classes/common.yml
kapitan/inputs/templates/inventory/classes/my_component.yml
kapitan/inputs/templates/inventory/targets/my_target.yml
kapitan/inputs/templates/templates/docs/my_readme.md
kapitan/inputs/templates/templates/scripts/my_script.sh
tests/test_initialiser.py

Fixes issue #90 
- Adds kapitan init as a new command. Recommendations on what further dirs/files should be created are welcome. :+1:

Fix #90: Initial work for kapitan init

---

README.md

Fix init command

---

.gitignore
.travis.yml
CONTRIBUTING.md
Makefile

Fixes issue #209 
- Test coverage range in Travis
- Fail if it's below our current 51%

Add test coverage check to travis CI, fail if under 51%

---

CHANGELOG.md
README.md
kapitan/utils.py
tests/test_version.py

- Fixes #232
- Added version check tests
- Updated CHANGELOG.md

Fixed and updated kapitan version checking

---

README.md
kapitan/inputs/jinja2_filters.py
kapitan/utils.py
tests/test_jinja2.py

- Refactored the loading process of custom jinja2 filters
- Added a few more custom filters from https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/core.py
- Added tests for new filters
Fixes #214

Added more and refactored jinja2 filters

---

CHANGELOG.md
scripts/inc_version.sh

Added a "." after the v in the previous release. Fixing now.  :slightly_frowning_face:

Start release-v0.23.0

---

examples/terraform/README.md
examples/terraform/compiled/project2/terraform/kubernetes.tf.json
examples/terraform/compiled/project3/terraform/kubernetes.tf.json
examples/terraform/templates/terraform/kubernetes.jsonnet
examples/terraform/templates/terraform/main.jsonnet
tests/test_terraform_compiled/project2/terraform/kubernetes.tf.json
tests/test_terraform_compiled/project3/terraform/kubernetes.tf.json

Fix Terraform examples to include kubernetes templates

---

MANIFEST.in

Follow up on https://github.com/deepmind/kapitan/pull/286

Include requirements.txt in pypi package.

---

README.md
docs/kap_proposals/kap_0_kadet.md

Related to https://github.com/deepmind/kapitan/pull/289 
I thought of organizing long-lasting changes to kap_proposals in the same way python has PePs just so we  have them grouped in one place.

Add kap_proposals in docs

---

docs/kap_proposals/kap_5_ref_types_redesign.md

KAP 5 - Ref Types Redesign

---

kapitan/targets.py

Fixes issue https://github.com/deepmind/kapitan/issues/272 
This is just a sample implementation draft for discussion.
-Updates jsonchema for validation of output_type based on input type before invoking compilation threads.

updated validation schema for compile

---

requirements.txt

jsonnet changelog
https://github.com/google/jsonnet/releases/tag/v0.13.0

Upgrade to jsonnet 0.13.0

---

Dockerfile.ci

Fixes issue #313
add `kapp` and `kbld` from https://k14s.io/

Add kapp and kbld to kapitan-ci

---

CHANGELOG.md

Start release-v0.24.0-rc.0

---

requirements.txt

Make boto3 requirement more flexible

---

CHANGELOG.md

Another rc release for testing. :) 
Many thanks to @yoshi-1224 and @caioaao  !

Start release-v0.24.0-rc.2

---

CONTRIBUTING.md

- Fix formatting.
- Update section for submitting changes to include info about forking.
- Add section about setting up environment (especially about updating submodule).
- Add info about running local development version.

Update CONTRIBUTING.md doc

---

Dockerfile.ci

Fixes issue #328
Upgrades Kapp in Dockerfile.ci to 0.10.0

update kapp to 0.10.0

---

README.md
kapitan/cached.py
kapitan/cli.py
kapitan/inputs/jinja2_filters.py
kapitan/refs/base.py
kapitan/utils.py
tests/test_jinja2.py

reveal_maybe filter, random cleanups

---

CHANGELOG.md

Another RC for testing multistage built docker images.
Kudos to @taharah for this :)

Start release-v0.24.1-rc.2

---

CHANGELOG.md

New release for testing. 
Changelog is already updated so I just did a no-op change.

Start release-v0.24.1-rc.3

---

docs/usage.md
examples/kubernetes/lib/custom_jinja2_filter.py
kapitan/dependency_manager/base.py
kapitan/initialiser.py
kapitan/inputs/kadet.py
kapitan/lint.py
kapitan/refs/secrets/vaultkv.py
kapitan/resources.py
kapitan/targets.py
requirements.txt
tests/test_cli.py
tests/test_helm_input.py
tests/test_initialiser.py
tests/test_vault.py

Fixes issue #381
- Update .kapitan file documentation
- Fix a lot of python linter errors
- Upgrade jsonnet, git and hvac dependencies

Fix issue 381

---

CHANGELOG.md

Start new RC release for the breaking changes to secrets + new vault functionality + jsonschema jsonnet function.

Start release-v0.25.0-rc.1

---

kapitan/targets.py

Raise CompileError instead of logging for compile labels

---

Dockerfile.ci

https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#01210-october-07-2019

upgrade to TF 0.12.10 in Dockerfile.ci

---

kapitan/refs/base.py
tests/test_cli.py

Add support for revealing files in subdirectories

---

kapitan/targets.py
tests/test_compile.py

Restore old order in compile_targets to fix process fork issue

---

kapitan/inputs/templates/components/my_component/my_component.jsonnet

Fix template for kapitan init so that the results compiles out of the box

---

docs/compile.md
kapitan/lib/kapitan.libjsonnet
kapitan/resources.py
tests/test_jsonnet.py
tests/test_resources/test_yaml_load_stream.yaml

add kap.yaml_load_stream() function

---

kapitan/inputs/base.py

`glob.glob` returns an empty array if it cannot resolve the provided
path, regardless of whether the provided path contains a globbed element
or not.
This commit reorganized the code in `compile_obj` and `compile_input_path`
to take into account the provided search paths during globbing.  As a
side-effect we always call `compile_input_path` with a fully resolved
path to the input file, and do not need to search the file in all search
paths again.
The CompileError for inputs which are not found has been moved to the
globbing phase, and is raised when `glob.glob` returns an empty array
for a given `input_path` in all provided search paths.
Fixes issue: no issue filed
- Fix `compile_obj` to take search paths into consideration when resolving globbed paths

Fix input_paths globbing when search paths are defined

---

kapitan/resources.py
tests/test_jsonnet.py

Correctly named branch this time to trigger the new rc release.
Fixed some small linter warnings.

Fix minor linter warnings and start release-v0.26.0-rc.1

---

docs/compile.md
examples/kubernetes/compiled/minikube-mysql/manifests/mysql_app.yml
examples/kubernetes/compiled/minikube-mysql/manifests/mysql_secret.yml
examples/kubernetes/compiled/minikube-mysql/manifests/mysql_secret_subvar.yml
examples/kubernetes/compiled/minikube-mysql/manifests/mysql_service_jsonnet.yml
examples/kubernetes/compiled/minikube-mysql/manifests/mysql_statefulset.yml
examples/kubernetes/inventory/classes/component/mysql.yml
examples/terraform/inventory/classes/type/terraform.yml
kapitan/inputs/base.py
kapitan/inputs/jsonnet.py
tests/test_kubernetes_compiled/minikube-mysql/manifests/mysql_app.yml
tests/test_kubernetes_compiled/minikube-mysql/manifests/mysql_secret.yml
tests/test_kubernetes_compiled/minikube-mysql/manifests/mysql_secret_subvar.yml
tests/test_kubernetes_compiled/minikube-mysql/manifests/mysql_service_jsonnet.yml
tests/test_kubernetes_compiled/minikube-mysql/manifests/mysql_statefulset.yml

Fixes issue #444 
- Enables per compile output prune
User can now explicitly setup a prune policy on a per compile output basis

444: Enables per compile output prune

---

docs/compile.md

Update references to jinja2 in docs

---

docs/external_dependencies.md
kapitan/dependency_manager/base.py

Always re-pull dependencies with --fetch

---

examples/kubernetes/compiled/labels/labels/service.yml
examples/kubernetes/compiled/labels/pre-deploy/00_namespace.yml
examples/kubernetes/compiled/labels/pre-deploy/10_serviceaccount.yml
examples/kubernetes/components/labels/service.yml
examples/kubernetes/inventory/classes/common.yml
examples/kubernetes/inventory/classes/component/labels.yml
examples/kubernetes/inventory/targets/labels.yml
examples/kubernetes/templates/labels.j2
kapitan/inputs/jinja2.py
kapitan/resources.py
kapitan/utils.py
tests/test_jinja2.py
tests/test_kubernetes_compiled/labels/labels/service.yml
tests/test_kubernetes_compiled/labels/pre-deploy/00_namespace.yml
tests/test_kubernetes_compiled/labels/pre-deploy/10_serviceaccount.yml

Fixes issue #473
- the jinja2 input now uses the search_paths when rendering
- the jinja2_render_file jsonnet callback now uses the search_paths when rendering

Support search paths in jinja2

---

docs/compile.md

Fixes issue #255
I was not too sure about how detailed to be and if the location was appropriate. I made the best effort to ensure compatibility with other sections of that particular page. My main aim was to ensure people can build up on the examples.
- Add kadet documentation

Add kadet usage documentation

---

kapitan/inputs/base.py

Check if input obj is None before writing to disk

---

docs/example-terraform.md
mkdocs.yml

Fixes issue #483 
This add the Terraform example documentation as described in the issue. I attempted to explained things the way I understood. 
I also made sure to perform spell/grammer checking to avoid wasting your time while performing the review.
- Add Terraform usage example documentation

Terraform example docs

---

docs/example-terraform.md
examples/terraform/compiled/project3/terraform/modules.tf.json
examples/terraform/inventory/targets/sandbox/project3.yml
examples/terraform/templates/terraform/main.jsonnet
examples/terraform/templates/terraform/modules.jsonnet
tests/test_terraform_compiled/project3/terraform/modules.tf.json

Fixes issue #483
The Jsonnet in this example is fairly simple. The purpose was to demonstrate the concept of the idea.
- Add Terraform collaboration example

Add Terraform collaboration example

---

CHANGELOG.md
docs/secrets.md
examples/terraform/compiled/project1/scripts/common.sh
examples/terraform/compiled/project2/scripts/common.sh
examples/terraform/compiled/project3/scripts/common.sh
examples/terraform/templates/scripts/common.sh
tests/test_terraform_compiled/project1/scripts/common.sh
tests/test_terraform_compiled/project2/scripts/common.sh
tests/test_terraform_compiled/project3/scripts/common.sh

Fix minor script in examples/terraform/scripts/common.sh 
Update docs about the new embedded refs functionality and start a new minor rc release.

Fix common.sh script in terraform example and start release-v0.27.3-rc.0

---

.gitmodules
CHANGELOG.md
Dockerfile
Dockerfile.ci
Dockerfile.pyinstaller
requirements.txt

And also start release-v0.27.3-rc.1

Update pip dependencies and reclass to latest versions

---

kapitan/cli.py
kapitan/initialiser.py
kapitan/lint.py
kapitan/refs/cmd_parser.py
kapitan/resources.py
kapitan/targets.py
kapitan/utils.py
tests/test_initialiser.py
tests/test_linter.py

Handle function calling logic in argparse instead of using equals  operator on strings. Also add aliases for all commands and move some functions under refs/ to reduce code file size

Handle function calling logic in argparse instead of using equals 

---

kapitan/refs/secrets/vaultkv.py
tests/test_vault.py

Fixes issue #511
- Raise encountered Vault errors

Vaultkv Error Handling

---

kapitan/lib/kapitan.libjsonnet
kapitan/resources.py
tests/test_jsonnet.py

Made this since it was discussed in our slack channel as a useful feature today.

Add file_exists function to jsonnet and kapitan.libjsonnet as well as a small unit test for it

---

docs/compile.md
kapitan/lib/kapitan.libjsonnet
kapitan/resources.py
tests/test_jsonnet.py
tests/test_jsonnet/file1.txt
tests/test_jsonnet/file2.txt
tests/test_jsonnet/subfolder2/file1.txt

Adding two additional dir handling bindings for jsonnet.

adding dir_files_list and dir_files_read in jsonnet

---

CHANGELOG.md
examples/kubernetes/inventory/classes/component/elasticsearch.yml
examples/kubernetes/inventory/classes/component/mysql.yml
examples/kubernetes/inventory/classes/component/namespace.yml
examples/kubernetes/inventory/classes/component/nginx-jsonnet.yml
examples/kubernetes/inventory/classes/component/nginx-kadet.yml
examples/kubernetes/inventory/targets/all-glob.yml
examples/terraform/inventory/reclass-config.yml
kapitan/inputs/jsonnet.py
kapitan/inputs/kadet.py
kapitan/targets.py
kapitan/utils.py

Allow using .yaml output file extension along with .yml and start release-v0.28.0-rc.1

---

docs/external_dependencies.md
docs/secrets.md

update helm-type link, mention Tesoro for secret refs

---

tests/test_remote_inventory/environment_one/README.md
tests/test_remote_inventory/environment_one/inventory/targets/remoteinv-example.yml
tests/test_remote_inventory/environment_one/templates/docs/README.md
tests/test_remote_inventory/environment_two/README.md
tests/test_remote_inventory/environment_two/inventory/targets/remoteinv-nginx.yml

Test resources for #521 
- It contains dummy inventories to test the recursive fetching of inventory items.

Remote inventory test resources

---

.gitignore
Pipfile
Pipfile.lock
docs/compile.md
kapitan/inputs/jinja2_filters.py
requirements.txt
tests/test_jinja2.py

Fixes issue #
- Bake in the jinja2 TOML filter support.

Add TOML Jinja2 Filters

---

tests/test_remote_inventory/environment_one/inventory/targets/remoteinv-example.yml
tests/test_remote_inventory/environment_two/inventory/targets/remoteinv-nginx.yml

Fixes issue #531 
Fixed the subdirectory path that points to the dummy inventories.

Subdirectory path fix

---

docs/compile.md
docs/secrets.md

Docs: update old ref type with base64 type

---

CHANGELOG.md
kapitan/remoteinventory/fetch.py
kapitan/targets.py
tests/test_remote_inventory/environment_one/inventory/targets/remoteinv-example.yml
tests/test_remote_inventory/environment_one/templates/docs/README.md
tests/test_remote_inventory/environment_two/inventory/targets/remoteinv-nginx.yml

Start release-v0.29.0-rc.1

---

docs/compile.md
docs/inventory.md

- Introduces the concept of "phases" during the compilation command

Improve documentation

---

docs/external_dependencies.md
docs/inventory.md

issue #521
- Add documentation for remote inventory federation 
- Update documentation of external dependencies

Docs: update documentation of inventory and external_dependencies 

---

CHANGELOG.md
kapitan/cli.py
kapitan/initialiser.py
kapitan/lint.py
kapitan/refs/base.py
kapitan/refs/cmd_parser.py
kapitan/remoteinventory/fetch.py
kapitan/utils.py
setup.py
tests/test_dependency_manager.py
tests/test_jsonnet.py
tests/test_remote_inventory.py
tests/test_vault.py

Doing a normal release as the last rc was live for a week without issues and it would be good to release now before more changes go in. :)

Start release-v0.29.0

---

kapitan/refs/base.py
tests/test_cli.py
tests/test_gpg.py

Fixes issue #604 
- Fix reveal from ref file bug
- Add test cases

Fix reveal from ref file bug

---

README.md
docs/README.md

Improve README.md

---

kapitan/resources.py
tests/test_jinja2.py

fix inventory_path not found error

---

README.md
docs/CI.md
docs/README.md
docs/example-kubernetes.md
docs/pyenv-scl.md
kapitan/cli.py
kapitan/utils.py
kapitan/version.py
mkdocs.yml
scripts/after_deploy.sh

Since the Kapitan project moved to the kapicorp GitHub org.

Update references to GitHub project

---

kapitan/refs/cmd_parser.py
kapitan/targets.py

- add json schema validation for kapitan secrets
- add KeyError exception handling for kapitan secrets

Handle KeyError in kapitan secrets

---

CHANGELOG.md

Start release-v0.29.5

---

kapitan/utils.py

Fixes issues #691 and #730 
- whitelist "application/x-compressed" and "application/x-compressed-tar" mime types for gzip-compressed tar dependencies

Add support for application/x-compressed and application/x-compressed-tar dependencies

---

docs/compile.md

fix "Phases of the compile command" markdown 

---

.github/workflows/docker-image.yml
.github/workflows/documentation.yml
.github/workflows/python-black.yml
kapitan/cli.py

- fix cli.py formatting
- fix docker image action

Build fixes

---

Dockerfile
requirements.txt

Build docker image with both jsonnet and gojsonnet

---

Pipfile
Pipfile.lock
pyproject.toml
requirements.txt

Requirements update

---

Dockerfile

Move from stretch to slim docker base image

---

.github/workflows/pex-build-upload.yml

Pex binary github actions workflow

---

kapitan/version.py

testing new release with pex artifact

0.30.0a2 to test pex build

---

.github/workflows/pex-build-upload.yml
kapitan/version.py

0.30.0a4 to test pex asset

---

.github/workflows/pex-build-upload.yml
kapitan/version.py

0.30.0a5 to test pex binary

---

.github/workflows/pex-build-upload.yml
kapitan/version.py

0.30.0a6 to test pex binary

---

Pipfile
Pipfile.lock
requirements.txt
setup.py

update jsonnet to 0.18.0

---

kapitan/version.py

- Releases 0.30.0
- Syncs reclass with latest fixes

Release 0.30.0

---

kapitan/refs/secrets/vaulttransit.py

Fixes issue #840 
- this adds the mount_point where it has never been implemented

closes kapicorp/kapitan#840

---

kapitan/inputs/kadet.py

Support lazy inventory in kadet

---

requirements.docs.txt

Fixes issue #879, #865
upgrade `requirements.docs.txt` to fix markdown rendering issues on [kapitan.dev](https://kapitan.dev)

#879: update pip requirements for docs

---

requirements.docs.txt

Fixes issue with requirements.txt

fix requirements.docs.txt

---

docs/contributing.md

Explicitly explain how to edit a page on the website.

Mention how to edit a webpage

---

docs/inventory.md

As the preview of the changes on github is limited, check my changes result in a correct output, especially regarding the modified  link and bullet lists  ;-)
Fixes issue #
-
-
-

Fix typos and link

---

docs/README.md
docs/compile.md
docs/contributing.md
docs/external_dependencies.md
docs/inventory.md
docs/kapitan_overview.md
docs/stylesheets/custom.css
mkdocs.yml
overrides/main.html

Updates site and documentation:
* fix links
* improve helm documentation
* fix installation
* adds sponsor and start badges
* change title

Update documentation and site

---

docs/README.md
docs/references.md

Improved documentation for references
* Documented example for YAML reference

Improved references documentation

---

kapitan/inputs/helm.py

Fixes issue #878
- Quickfix for flag `--indent` for helm input

Fix indent flag for helm input

---

kapitan/version.py

Release 0.31.0

---

docs/inventory.md

This change updates the wording in the targets examples to improve clarity. It also fixes the file extension in the **applications** example.

Update examples for targets in docs

---

docs/pages/blog/2023-01-16.md
mkdocs.yml
overrides/main.html

Blog post for new Kapitan release

New kapitan release

---

kapitan/refs/secrets/azkms.py
tests/test_linter.py

Satisfy new requirements from latest black release 
https://github.com/psf/black/releases/tag/23.1.0
Example of a build that was failing
https://github.com/kapicorp/kapitan/actions/runs/4079117500/jobs/7030144851

Linter fixes

---

README.md

Install pip and libmagic prior to pip install

Adds OS requirements for pip install to README

---

Dockerfile

Fix failed [Docker Build and Push](https://github.com/kapicorp/kapitan/actions/workflows/docker-image.yml) step after https://github.com/kapicorp/kapitan/pull/929
Failed run:
https://github.com/kapicorp/kapitan/actions/runs/4128201436/jobs/7132347350

Fix Dockerfile after poetry changes

---

overrides/main.html

Fix button for editing documentation not appearing on the website

Fix button for editing not appearing

---

docs/inventory.md
docs/kapitan_overview.md
docs/pages/blog/2022-12-04.md
mkdocs.yml

* fix a few typos here and there
* enable _abbreviations_ on the engine
* https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=abbr#abbreviations
* https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-abbreviations

✨ tidy up the docs a bit

---

mkdocs.yml

No favicon showing in docs page

Update favicon in docs

---

CHANGELOG.md

Only change is
https://github.com/kapicorp/reclass/pull/10

Sync reclass

---

Dockerfile

Fixes issue #961
* replace HELM_CACHE_HOME

Fix HELM_CACHE_HOME in Docker image

---

.gitignore

Groups entries in `.gitignore` logically and adds `.tool-versions` for the `asdf` package manager.

chore: reorganise .gitignore and add .tool-versions.

---

kapitan/inputs/jsonnet.py
kapitan/inputs/kadet.py

Fixes issue  a bug introduced by #982
PR #982 was botched in many ways. This should be the final fix
- fix the argument name mismatch

Fix bug in prune not being passed to inputs

---

kapitan/version.py
pyproject.toml

https://github.com/kapicorp/kapitan/releases/tag/v0.32.0-rc.0

Release 0.32.0rc0

---

docs/pages/contribute/talk.md
docs/support.md

Fixes issue #992 
- Fix invite link for Kapitan Slack -> https://slack.k8s.io/

Fix kapitan invite link

---

README.md

Fixes issue #
- Update README.md

chore(doc): Update with correct quick start link

---

Dockerfile

- remove empty file `requirements.txt`

chore: remove empty file `requirements.txt`

---

examples/terraform/inventory/classes/type/terraform.yml

Fixes #1018 
- Add correct target_name reference to support compose-node-name
---

fix(examples): add correct target_name reference

---

.github/workflows/test-build-publish.yml

Fixes issue #
- use correct docker upstream org env variable
-
-

Use correct upstream docker org

---

.github/workflows/documentation.yml
.github/workflows/test-build-publish.yml
Dockerfile.docs
requirements.docs.txt

Fixes issue #
- upgrade libraries and docker image for website
-
-

Upgrade docs libraries

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.yml

* added `Documentation Issue` template
* added `config.yml` to create links to Discussions and Slack

feat: add more issue forms and issue config

---

kapitan/utils.py

Reverts kapicorp/kapitan#1083 merged by mistake

Revert "fix: import libmagic only when its needed"

---

kapitan/refs/vault_resources.py

* improved error message when authentication to vault failed (important is the hint that the token could be expired)

feat(vault): improve error message for vault `authentication error`

---

mkdocs.yml

fix warning preventing docs build

---

.gitmodules
Dockerfile
poetry.lock
pyproject.toml

* Install `reclass` as a pip dependencies instead of submodule

Install reclass as pip package

---

.github/workflows/test-build-publish.yml
pyproject.toml

Remove support for Python 3.9

---

pyproject.toml

New Release 0.33.0-rc1

---

.github/workflows/test-build-publish.yml
kapitan/inputs/helm.py
tests/test_compile.py

chore: fix linter

---

pyproject.toml

Fix pip release for 0.33.0

---

.github/workflows/python-pip-publish.yml

Allow manual workflow for pip release

---

.github/workflows/documentation.yml

fix docs deployment

---

docs/ADOPTERS.md
docs/README.md
docs/pages/inventory/introduction.md
docs/pages/kapitan_overview.md
mkdocs.yml

Adds Adopters

---

requirements.docs.txt

Improved docs

---

docs/ADOPTERS.md

Fixes #
* add neXenio as Adopters

fix(docs): Add neXenio to Adopters

---

docs/ADOPTERS.md

* Added Airfund as adopters to Airfund

fix(docs): Add AirFund to adopters

---

docs/ADOPTERS.md

Adds Phaidra.ai to ADOPTERS.md

Add Phaidra to ADOPTERS.md

---

docs/ADOPTERS.md

Fixes #N/A
* Adds Skyscanner to list of adopters
* Quick re-order of existing list to alphabetically sort

Adopters - Add Skyscanner to list

---

docs/pages/commands/kapitan_compile.md
kapitan/cli.py
kapitan/inputs/base.py
kapitan/inventory/inv_reclass.py
kapitan/resources.py
poetry.lock

Fixes #
* Isolates the changes to allow for passing in the `compose-target-name`

Fix inventory not handling compose-target-name

---

kapitan/targets.py
tests/test_compile.py
tests/test_resources/inventory/targets/fail-compile.yml
tests/test_resources/kadet_functions/fail_compile/__init__.py

Fixes #
* adds "continue_on_compile_error" as compile object option

Continue on compile error

---

kapitan/inputs/base.py
kapitan/targets.py

Fix path not found when using compose-node

---

poetry.lock
pyproject.toml

Fixes #
* Upgrade version of poetry to 1.8.3

Upgrade version of poetry to 1.8.3

---

examples/kubernetes/compiled/jsonnet-env/jsonnet-env/env.yml
kapitan/inputs/base.py
kapitan/utils.py

Fixes #
* Improves Yaml pretty dumper for multiline

Improves Yaml pretty dumper for multiline

---

kapitan/utils.py
tests/test_compile.py
tests/test_inventory.py
tests/test_utils.py

Fixes #
* Fix minor issue detected in https://github.com/kapicorp/kapitan/pull/1183
* Adds tests

Fix copy tree

---

kapitan/cli.py
kapitan/resources.py

Fixes #
* Allows to select multiprocessing start method from the command line.

Add mp-method arg

---

.github/workflows/python-pip-publish.yml
kapitan/dependency_manager/base.py
kapitan/version.py
pyproject.toml

Fixes #
* Only download helm chart if needed. Skip if the output directory exists unless forced
* Remove test pipy deployment

Only download helm chart if needed

---

kapitan/cli.py
kapitan/inventory/__init__.py
kapitan/resources.py
poetry.lock
pyproject.toml
tests/test_compile.py
tests/test_compose_node_name.py
tests/test_from_dot_kapitan.py
tests/test_inventory.py
tests/test_omegaconf.py

Fixes #1210
* Improve loading of inventory backends

Fix #1210 and improves loading of inventory backends

---

mkdocs.yml
requirements.docs.txt

Fixes #
* Enable multi doc versioning with `mike`

Deploy mike

---

.github/workflows/documentation.yml

fix: Adds commit user and email for mike to commit correctly

---

.github/workflows/documentation.yml

Adds ability to deploy docs from master

---

.github/workflows/documentation.yml
.github/workflows/test-build-publish.yml

fix: fix path for documentation workflow

---

.github/workflows/documentation.yml
docs/pages/contribute/documentation.md

fix: fix docs with poetry

---

.github/workflows/pex-build-upload.yml

Fixes #838
* Fix pex package generation that has been broken for a while

Fix pex package generation

---

docs/pages/contribute/code.md
tests/test_compile.py
tests/test_inventory.py

Fix doc on how to contribute (from #1100)

---

kapitan/cli.py
tests/test_compile.py
tests/test_resources/inventory/targets/reveal-output.yml

Fixes #
* Reinstates https://github.com/kapicorp/kapitan/pull/1189

Reinstates missing PR

---

kapitan/version.py
poetry.lock
pyproject.toml

Release patch containing fixes to v0.34

---

MANIFEST.in
kapitan/__init__.py

Remove old references to reclass

---

kapitan/version.py
poetry.lock
pyproject.toml

Release Kapitan 0.34.3

---

kapitan/refs/cmd_parser.py

Fixes #1300
* fix key not being fetched correctly from configuration

fix:  #1300 fix key not being fetched from configuration correctly

---

kapitan/version.py
pyproject.toml

Release 0.34.5

---

kapitan/jinja2_filters.py
kapitan/version.py
pyproject.toml

release 0.34.7
