kapitan/resources.py
tests/test_inventory.py

This will simply allow to call inventory(target=null) and return a view of all target in the inventory as opposed to the default current target.

set inventory() target to null/None to get all targets

---

.travis.yml
examples/inventory/targets/minikube-es.yml
kapitan/cli.py
kapitan/secrets.py
requirements.txt
tests/test_secrets.py

This exposes a new **secrets** command to help write and reveal secrets with the goal of avoiding any sensitive data in templates or compiled files.
Every new secret requires a token path and recipients which will be written to a file structure generated by the --write argument. 
The content of a secret token file contains the GnuPG encrypted secret data and a list of recipient fingerprints.
Example of encrypting the content of files/secret_sauce into the app1/secret1 token:
```
$ echo "super secret data" > files/secret_sauce
$ kapitan secrets --write app1/secret1 --recipients human@example.com -f files/secret_sauce
```
Tokens can be used in templates and inventory and will not be revealed when compiled. Any compiled file with secrets will contain the secret token tags instead. 
A token …

Secrets with GnuPG support

---

kapitan/lib/kapitan.libjsonnet
kapitan/resources.py
tests/test_jsonnet.py

This native function allows rendering jsonnet object into YAML in runtime. Especially handy when you need to render a ConfigMap where the data is YAML.

new yaml_dump() native jsonnet function

---

kapitan/cli.py
kapitan/secrets.py
kapitan/targets.py
tests/test_secrets.py

We're introducing a new default behaviour for any compiled items using kapitan secrets: compiled secret tags. 
Compiled secret tags are a way of verifying that compiled items containing secret tags match the stored secrets. This is done by appending a checksum to the secret tag when compiling.
Checksumming is achieved by doing a sha256 of the token path plus the sha256 of the base64 of the encrypted secret (note, not the secret itself). The checksum is then trimmed to 8 chars.
The use case here is auditing the lifecycle of the stored secrets (via git) whilst allowing developers, CI systems, etc... (who won't have access to decryption keys) to compile and validate the stored secrets without being able to reveal them.
Create a secret:
```
$ echo -n "secret_thing_1" | kapitan secrets --write …
```

Compiled secret tags

---

kapitan/cli.py
kapitan/errors.py
kapitan/resources.py
kapitan/targets.py
kapitan/utils.py

This will log/print friendlier error messages avoiding tracebacks for known failure behaviours:
- inventory not found
- inventory render errors
- jsonnet compile errors
- jinja2 render errors (including jsonnet native calls)
Thus improving https://github.com/deepmind/kapitan/issues/11
Compiling will also now write to a tempdir and move it to output_path on success (tempdir is always removed)

improved errors, logging and compilation

---

kapitan/cli.py
kapitan/targets.py

The new behaviour for target compilation is to search for 'target.json' files within a target_path which defaults to "./targets".
So the new compile command will compile all targets found:
```
$ cd examples
$ kapitan compile
Compiled targets/minikube-es/target.json
```
The target path can be changed with a new flag:
```
$ kapitan compile --target-path ~/my/targets
Compiled /home/me/my/targets/name/target.json
```

Breaking change: only compiles all target files found

---

kapitan/secrets.py

Since python-gnupg does not respect/read the default key in ~/.gnupg/gpg.conf, this checks for the key expiry and returns the next valid one, should the recipient be associated to multiple keys.

Check for gpg key expiry

---

kapitan/cli.py
kapitan/secrets.py
tests/test_secrets.py

Add a new --base64 flag that when used with
```
$ kapitan secrets --write --base64 -f file_to_encrypt.txt
```
will base64 its content and then encrypt. It will also add a new 'encoding' key in the secret file to note that the original content was base64'd.
Essentially, this is equivalent of doing:
```
$ cat file_to_encrypt.txt | base64 | kapitan secrets --write my_secret --recipients person@example.com -f -
```
which is especially handy when using Kubernetes Secrets (which content needs to be base64'd)

base64 encode and write secret support

---

kapitan/cli.py
kapitan/secrets.py
kapitan/targets.py
tests/test_secrets.py

Added support for revealing directories with compiled files. The following:
```
$ kapitan secrets --reveal -f my_files/
```
Will keep output in memory until all files have been successfully revealed and will only then write to stdout.
Also on _secrets_ and _compile_ subcommands,  `--reveal`  will now recursively replace secret tags whenever possible (should they be json/yaml structured) and will fall back to search and replace on other formats.

improved revealing, added support for revealing files in directories

---

examples/kubernetes/inventory/targets/minikube-es.yml
examples/kubernetes/inventory/targets/minikube-mysql.yml
kapitan/cli.py
kapitan/secrets.py
kapitan/targets.py
kapitan/version.py
tests/test_secrets.py

Introduces a new feature of "target secrets".
Secrets are originally standalone but dealing with them at scale can become complicated, especially when one needs to add or remove recipients. The proposed solution is to organise secrets per target in their respective target directory (inside --secrets-path).
For the recipients below in the inventory for *my-target*:
```yaml
...
target_name: my-target
kapitan:
secrets:
recipients:
- name: person1@example.com
fingerprint: DEADBEEF
- name: person2@example.com
fingerprint: 8BADF00D
```
Creating a secret for target *my-target*:
```
$ kapitan secrets --write targets/my-target/secret_sauce -t my-target -f my_data
Wrote secret targets/my-target/secret_sauce for fingerprints DEADBEEF, 8BADF00D at ./secrets/targets/my-target/secret_sauce
```
Let's …

Target secrets support

---

Dockerfile
README.md
ci/Dockerfile
ci/README.md

- New Docker image `deepmind/kapitan:ci` to be used in CI/CD pipelines. Comes with `gcloud`, `kubectl` and `kapitan`.
- Docs

CI/CD usage with Docker

---

kapitan/targets.py

Applies to `compile -t <target>`, if `compiled/<target>` doesn't exist in the first place, compilation will fail.

Create compiled target directory if it doesn't exist

---

Dockerfile
ci/Dockerfile

updating the package cache is IMHO not needed since the 
> --no-cache
option will pull directly from the online repos anyway. 
(with the small benefit of around 1MB for the package cache)
if you do this to avoid caching of the layers while building i suggest to build with the --no-cache option from docker:
`docker build --no-cache `
All the best

remove not needed command

---

Dockerfile
ci/Dockerfile
requirements.txt

updated gnupg to 0.4.2 as suggested in requirements.txt 
released on 28.03.2018 
https://github.com/vsajip/python-gnupg
tested the build, screenshot below

Gnu update

---

ci/Dockerfile

The date command available on busybox is too limited
This install the GNU version of date

Add coreutils to ci/Dockerfile

---

kapitan/cached.py
kapitan/resources.py
kapitan/targets.py

Fixes #25 
- Save `inventory_reclass` output as a cached variable in `cached` module, initialized only once. No need to complicate ourselves with `multiprocessing.Manager` as inventory is read-only in threads and doesn't change.
- Saves ~8-10s on `kapitan compile`

Cache inventory (reclass) across multiple threads

---

.gitignore
kapitan/cli.py
kapitan/targets.py
kapitan/utils.py
kapitan/version.py

Addresses #57 
- `kapitan compile` now writes the version to `.kapitan` and future executions will check if the last used kapitan version is <= than current kapitan version. If the last version is bigger than current version, it will output something like:
```
Current version: 0.15.0
Last used version (in .kapitan): 0.15.1
Please upgrade kapitan to at least "0.15.1" in order to keep results consistent:
Docker: docker pull deepmind/kapitan
Pip (user): pip3 install --user --upgrade git+https://github.com/deepmind/kapitan.git --process-dependency-links
Pip (system): sudo pip3 install --upgrade git+https://github.com/deepmind/kapitan.git --process-dependency-links
```
- `kapitan compile --ignore-version-check` option for cases when you don't want the check such as CI.
- Version increment …

Enforce kapitan version

---

.travis.yml
Dockerfile
README.md
ci/Dockerfile
kapitan/cli.py
kapitan/resources.py
kapitan/utils.py
requirements.txt

salt-formulas/reclass#25 was merged yesterday so moved reclass commit reference to latest develop.
Reclass are overwriting the default pip install prefix so I had to add `--prefix=/usr/local` to the Docker images and Travis. Once https://github.com/salt-formulas/reclass/pull/28 is merged, we can remove the `--prefix`.

Updated reclass

---

kapitan/errors.py
kapitan/secrets.py
kapitan/targets.py
tests/test_secrets.py

This introduces support for creating a target secret on compile time, if the secret does not already exist.
Target secrets have been introduced a few commits ago and have proven to work well. However when using reclass inventory interpolation for target secret tags, you will be forced to create all of the interpolated target secrets manually as compilation will fail.
To solve this problem, this PR proposes the following new (optional) form of secret tags:
`?{gpg:path/to/new_secret|randomstr:32}`
Or interpolating `${target_name}`:
`?{gpg:targets/${target_name}/new_secret|randomstr:16}`
If `path/to/new_secret` does not exist under `secrets_path` it evaluates `randomstr:32`, a function supported in this PR, which returns a 32 (as parameterised) byte-log random string generated by …

target secret functions support

---

Dockerfile
README.md
ci/Dockerfile
kapitan/cli.py
kapitan/resources.py
kapitan/secrets.py
kapitan/targets.py
kapitan/utils.py
requirements.txt

- Switch to `ujson` for better json parsing performance
- Use `yaml.CSafeLoader` if C bindings for yaml lib are available. Output does not change. I have omitted the `yaml.CDumper` usage for now as a fallback would change the compilation output.
- Keep `print` consistent by using `{}.format()` instead of `f"{}"` (only 3.6+)
- Light refactoring and removed unused function `load_target_file`

Optimisations

---

kapitan/cli.py
kapitan/utils.py

Right now we have to specify the whole path when we search for variables using `searchvar` like:
```
kapitan searchvar parameters.mysql.storage_class
```
We want to be able to just specify:
```
kapitan searchvar storage_class
```
Or even:
```
kapitan searchvar storage_*
```
This also applies to `kapitan inventory -t <target> -p <filter>`:
```
kapitan inventory -t minikube-mysql -p storage_*
```

Allow recursive search and globbing in searchvar and inventory commands

---

README.md
examples/kubernetes/compiled/minikube-mysql/manifests/mysql_secret.yml
examples/kubernetes/components/mysql/secret.jsonnet
examples/kubernetes/inventory/classes/component/mysql.yml
kapitan/secrets.py
requirements.txt
tests/test_compile.py
tests/test_kubernetes_compiled/minikube-mysql/manifests/mysql_secret.yml

- Added support for RSA private keys `?{gpg:common/rsa.key|rsa}` (default 4096) with optional param `rsa:<key size>`
- Added support for pipes in functions `?{gpg:mysql/root/password|randomstr|base64}`
- Added sha256 function `?{gpg:mysql/root/password|randomstr|sha256}` with optional param `sha256:<salt>`
- Deprecated `|randomstrb64` in favor of `|randomstr|base64`
- Updated docs to include info about secrets and to better reflect the current examples.
Fixes #84 and #100

Secrets functions refactoring

---

README.md
examples/kubernetes/compiled/minikube-mysql/manifests/mysql_secret.yml
examples/kubernetes/components/mysql/secret.jsonnet
examples/kubernetes/inventory/classes/component/mysql.yml
kapitan/secrets.py
requirements.txt
tests/test_compile.py
tests/test_kubernetes_compiled/minikube-mysql/manifests/mysql_secret.yml

#102 got git confused so retrying here.
- Added support for RSA private keys `?{gpg:common/rsa.key|rsa}` (default 4096) with optional param `rsa:<key size>`
- Added support for pipes in functions `?{gpg:mysql/root/password|randomstr|base64}`
- Added sha256 function `?{gpg:mysql/root/password|randomstr|sha256}` with optional param `sha256:<salt>`
- Deprecated `|randomstrb64` in favor of `|randomstr|base64`
- Updated docs to include info about secrets and to better reflect the current examples.
Fixes #84 and #100

Secrets functions refactoring (retry)

---

README.md
kapitan/cli.py
kapitan/targets.py

- Added `kapitan compile --indent x` or `kapitan compile -i x` to customize indentation of yaml and json
- Changed default indent to 2 so all outputs are consistent (json was previously on 4 and yaml on 2)
Fixes #109

Customizable indentation of yaml/json

---

.gitmodules
.travis.yml
README.md
ci/Dockerfile
kapitan/__init__.py
kapitan/utils.py
requirements.txt
setup.py
tests/test_compile.py
tests/test_inventory.py
tests/test_jinja2.py
tests/test_jsonnet.py
tests/test_secrets.py

- Updated reclass to latest master v1.5.3
- Importing as git submodule with v1.5.3 checked out
- Removed deprecated `--process-dependency-links` pip install flag and references
- Light cleanup
We can push kapitan to pip after merging and minor release

Reclass update and import as submodule

---

kapitan/cli.py
kapitan/utils.py

- `--verbose/-v` on `kapitan inventory` and `kapitan searchvar`
- Debug log when serialization fails on `hashable_lru_cache`

More verbose options

---

kapitan/cached.py
kapitan/cli.py
kapitan/resources.py
kapitan/secrets.py
kapitan/targets.py
tests/test_secrets.py

- Init GPG backend when required and store in cached module
- Removed the GPG backend object from function params

Secrets GPG backend usage refactor

---

README.md
kapitan/secrets.py

https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.PrivateFormat
`PKCS8` recommended over `TraditionalOpenSSL`.

Updated RSA key format to PKCS#8

---

kapitan/cli.py
kapitan/utils.py

BEFORE
```
$ kapitan searchvar parameters.kapitan.compile
./inventory/targets/global.yml                           [{'input_paths': ['docs/global/'], 'input_type': 'jinja2', 'output_path': 'docs'}]
./inventory/targets/auto-deploy.yml                      [{'input_paths': ['scripts/ci/'], 'input_type': 'jinja2', 'output_path': 'scripts'}]
```
AFTER
```
$ kapitan searchvar parameters.kapitan.compile -p
./inventory/targets/global.yml
- input_paths:
- docs/global/
input_type: jinja2
output_path: docs
./inventory/targets/auto-deploy.yml
- input_paths:
- scripts/ci/
input_type: jinja2
output_path: scripts
```

Add pretty_printer option to searchvar

---

README.md
kapitan/cached.py
kapitan/cli.py
kapitan/errors.py
kapitan/resources.py
kapitan/targets.py
kapitan/utils.py

Resolves #111 
- Doc strings consistent with PEP 257
- Allows configuration of command flags in `.kapitan`, such as:
```
version: 0.17.0
compile:
indent: 4
```
will translate to `kapitan compile --indent 4`
- Enforcing kapitan version from `.kapitan`
- `.kapitan` usage doc

Command flags support in .kapitan

---

README.md
kapitan/cli.py
kapitan/resources.py
kapitan/targets.py
tests/test_inventory.py
tests/test_jinja2.py

- Enables searching for jsonnet and jinja2 files in multiple paths.
- Renamed `--search-path` to `--search-paths` in `eval` and `compile` commands.
Fixes #132

Support for multiple --search-paths

---

kapitan/cli.py

```
$ ~/git/kapitan/bin/kapitan compile -t my_target -f
usage: kapitan compile [-h] [--search-paths JPATH [JPATH ...]] [--verbose]
[--prune] [--quiet] [--output-path PATH]
[--targets TARGET [TARGET ...] | --force-recompile]
[--parallelism INT] [--indent INT]
[--secrets-path SECRETS_PATH] [--reveal]
[--inventory-path INVENTORY_PATH]
[--ignore-version-check]
kapitan compile: error: argument --force-recompile/-f: not allowed with argument --targets/-t
```

compile arguments force-recompile and targets are mutually exclusive

---

kapitan/resources.py

More info:
https://github.com/salt-formulas/reclass/releases/tag/v1.5.6

update reclass to release v1.5.6

---

README.md
kapitan/cli.py
kapitan/refs/secrets/gpg.py
kapitan/utils.py
tests/test_cli.py
tests/test_gpg.py

Fixes encoding issues when creating gpg secrets using the cli (#150)
Fixes wrong file argument in cli.py
Breaking change: removes --backend in secrets subcommand. New format for secret token in cli is prefix with backend name (now referred as type_name) e.g. gpg:path/to/secret1
Refactor of cli code into smaller functions easier to test.
Test secret cli write and reveal

Fix cli secrets

---

README.md
examples/kubernetes/inventory/classes/common.yml
examples/kubernetes/inventory/classes/component/mysql.yml
kapitan/cached.py
kapitan/cli.py
kapitan/refs/base.py
kapitan/refs/secrets/awskms.py
requirements.txt

Add support for AWS KMS as a secrets backend

---

Makefile
kapitan/cli.py
kapitan/inputs/base.py
kapitan/inputs/jinja2.py
kapitan/inputs/jsonnet.py
kapitan/refs/secrets/awskms.py
kapitan/targets.py

Introduces a new InputType class which serves as the base class for 2 new input_type compilers:
* Jsonnet
* Jinja2
Also fixes minor code style issues

Refactor input_type code into classes

---

CHANGELOG.md
kapitan/cli.py
kapitan/inputs/base.py
kapitan/inputs/jinja2.py
kapitan/refs/base.py
kapitan/refs/secrets/awskms.py
kapitan/refs/secrets/gkms.py
kapitan/refs/secrets/gpg.py
kapitan/targets.py
kapitan/utils.py

Some more no-op cleanup + a breaking change since there is one more in this release candidate.
Specifically:
- fix various codestyle errors
- fix a TODO with missing exception handling
- simplify os.makedirs everywhere
- move search_target_token_paths to kapitan.utils since it's only used in cli and is not logically bound to kapitan/refs/base.py
- Update changelog

Minor cleanup

---

CHANGELOG.md

This will trigger docker builds with the latest fixes from #204

Starting release for deepmind/release-v0.22.2

---

README.md
kapitan/cli.py
tests/test_cli.py

Fixes issue #241 
Adds support for creating ref type secrets via command line:
```
$ kapitan secrets --write ref:my_password -f <(echo -n password123)
```

Add support for writing ref type secrets in command line

---

kapitan/targets.py
tests/test_compile.py

Fixes issue #203, #147 
Before compilation, validates whether each target name has a corresponding target yml file in inventory. Target name is derived from `vars.target`. Should this parameter not be set, the following error is given:
```
Target missing: target "<target_filename>" is missing parameters.kapitan.vars.target
This parameter should be set to the target name
```
If the target name does not match the file name, the following error message is provided:
```
Target "<target_name>" is missing the corresponding yml file in <abs_inventory_path>/targets
Target name should match the name of the target yml file in inventory
```

Validate target name matches target yml file name

---

kapitan/cli.py
kapitan/lint.py
requirements.txt
tests/test_linter.py
tests/test_resources/inventory/classes/component/mysql.yml

Adds a yaml lint check for every file in a given inventory to help debug yaml issues.
Uses a very relaxed yamllint config by default but can be overriden with the rules in a local '.yamlllint' file if that file exists.
Rules taken from https://yamllint.readthedocs.io/en/stable/rules.html

Add yamllint in kapitan linter checks

---

README.md

Fixes the README for `kapitan secrets --reveal` part.
We cannot do 
```
kapitan secrets --reveal -f examples/kubernetes/compiled/minikube-mysql/manifests/mysql_secret.yml
```
because inside mysql_secret.yml, the ref path is `targets/minikube-mysql/mysql/password`.
Also possible to do
```
kapitan secrets --reveal --secrets-path examples/kubernetes/secrets -f examples/kubernetes/compiled/minikube-mysql/manifests/mysql_secret.yml
```

Fix secrets --reveal path in README

---

CHANGELOG.md
requirements.txt

We haven't done an rc release in a while and it's good to keep a candidate release out there before actually releasing an update.

Update reclass and addict dependencies, start 0.23.1-rc.0 release

---

examples/docker/compiled/docker/jsonnet/Dockerfile.web
examples/docker/compiled/docker/jsonnet/Dockerfile.worker
examples/docker/compiled/docker/kadet/Dockerfile.web
examples/docker/compiled/docker/kadet/Dockerfile.worker
examples/docker/components/jsonnet/jsonnet.jsonnet
examples/docker/components/kadet/__init__.py
examples/docker/inventory/classes/dockerfiles.yml
examples/docker/inventory/targets/docker.yml
examples/docker/templates/Dockerfile
kapitan/inputs/jsonnet.py
kapitan/inputs/kadet.py
tests/test_compile.py
tests/test_docker_compiled/docker/jsonnet/Dockerfile.web
tests/test_docker_compiled/docker/jsonnet/Dockerfile.worker
tests/test_docker_compiled/docker/kadet/Dockerfile.web
tests/test_docker_compiled/docker/kadet/Dockerfile.worker

This adds support for...
```yaml
- input_type: jsonnet
output_type: plain
```
...and...
```yaml
- input_type: kadet
output_type: plain
```
...as per discussion in [`#kapitan`](https://kubernetes.slack.com/archives/C981W2HD3/p1557149564137100).

Make jsonnet & Kadet support for plain text output_type

---

CHANGELOG.md

```
- Fix pypi package by including requirements.txt (#287)
- Make jsonnet & kadet support plain text output_type (#288)
- Fallback to reclass 1.5.6 because of regression (#284)
- Add parseYaml function in jsonnet (#263)
- Add support for specifying custom jinja2 filters (#267)
- Update minor dependencies (#283)
```

Start release-v0.23.1

---

README.md

Without this when trying to generate a secret it gives the following error: `Could not create GPGSecret: target_name missing`

Fix GPG recipients config

---

requirements.txt

Fixes issue #295 
requests module update from 2.21.0 to 2.22.0 is breaking the test. For the time being, it makes sense to fix it at 2.21.0.

Fix requests version to circumvent urllib3 version conflict

---

kapitan/targets.py

While doing #317 I noticed that ValidationError raised in `valid_target_obj(target_obj)` is treated as 
`Unknown (Non-Kapitan) Error ocurred`, with stacktrace printed, since it is not an instance of Kapitan Error. This PR changes the raised error to InventoryError to better handle it, as well as to make the error message more readable.
say `output_path` was misspelt as `output_pth`.
```
Unknown (Non-Kapitan) Error occured
File "/home/yoshi/.local/lib/python3.6/site-packages/kapitan/targets.py", line 69, in compile_targets
target_objs = load_target_inventory(inventory_path, updated_targets)
File "/home/yoshi/.local/lib/python3.6/site-packages/kapitan/targets.py", line 285, in load_target_inventory
valid_target_obj(target_obj)
File …
```

Improve json schema validation error display for inventory

---

examples/kubernetes/compiled/minikube-mysql/manifests/mysql_app.yml
examples/kubernetes/components/mysql/main.jsonnet
kapitan/inputs/base.py
kapitan/refs/base.py
tests/test_kubernetes_compiled/minikube-mysql/manifests/mysql_app.yml

This way we can have a multi-document yaml file (see [this](https://pyyaml.org/wiki/PyYAMLDocumentation#dumping-yaml) for more info).
As an example, consider this jsonnet:
```jsonnet
{
'foo': [
{'a': 1}, {'a': 2}, {'a': 3}
]
}
```
Previously the output (when type=yaml) would be:
```yaml
- a: 1
- a: 2
- a: 3
```
With this change, it's:
```yaml
a: 1
---
a: 2
---
a: 3
```

Multi-document yaml outputs

---

_config.yml
docs/CNAME

Docs have been deployed to gh-pages based on instructions from https://www.mkdocs.org/user-guide/deploying-your-docs/ 
This PR also removes the old _config.yml jekyll configuration and updates the CNAME of the custom domain for the gh page. 
Followup from #331

Fix gh-pages domain, remove old jekyll config

---

.gitignore
README.md
docs/README.md
docs/contributing.md
mkdocs.yml

- Move Contributing.md to docs/ and link to it on the website
- Ignore site/ in git since that's the compiled mkdocs output.
- Cleanup README.md from duplicate info also included in docs/README.md
- Remove unnecessary Table of Contents in docs/README.md since that's generated via mkdocs.yml automatically and will cause confusion if repeated.
- Add instructions for doc local testing and deploying to github.

Deduplicate README and add instructions for publishing to gh-pages.

---

docs/README.md
docs/compile.md
docs/example-kubernetes.md
docs/external_dependencies.md
mkdocs.yml

- Add some documentation for how `examples/kubernetes` works
- Add `usage.md` to the nav bar
- Fix some other syntax issues and clarify some parts of the documentation
- add examples for helm input and external dependency
- add the information that kapitan binary is available (when #323 is done)

More examples and some minor documentation fixes

---

kapitan/dependency_manager/base.py
tests/test_dependency_manager.py
tests/test_resources/inventory/targets/nginx-dev.yml

We allow users to download `.zip`, `.tar.gz` files etc. and unpack them onto `output_path`. There are a few  issues with the way I implemented some of the stuff
1. we use the content-type in HTTP header to decide the file type to unpack. There are some files, such as the charts at `https://helm.nginx.com/stable/index.yaml` whose extensions are `.tgz` but the content-type is `application/octet-stream`. In such cases, we should just look at the extension using regex and decide how to unpack this file
2. when unpacking archive files, the parent directory should be allowed to be the `output_path` into which the files are extracted. For example, if we want to download a helm chart `nginx-ingress` then we should be able to do:
```yaml
- type: https
source: …
```

Fix dependency manager's behaviour for files to unpack

---

.travis.yml
CHANGELOG.md
Dockerfile.ci
requirements.txt

- Update some packages in pypi
- Update kapp and kbld in dockerfile.ci
- Start  release-v0.24.0-rc.4 
Last RC before actual release.

Start release-v0.24.0-rc.4

---

.travis.yml
CHANGELOG.md
scripts/pyinstaller.sh

This fixes the build https://travis-ci.org/deepmind/kapitan/builds/575779357
which if I understand correctly failed to package kapitan for pypi because  of the previous resources on filesystem from the releases build step. 
Also rename standalone binary released to kapitan-linux-amd64 so it's more clear exactly what it is for.

Remove skip_cleanup in travis, rename standalone binary to kapitan-linux-amd64

---

.gitignore
.travis.yml
CHANGELOG.md
Makefile
scripts/build-binary.sh
scripts/pyinstaller.sh

In an effort to fix this https://github.com/deepmind/kapitan/issues/345 
I added dist/kapitan-linux-amd64 to the list of artifacts that will be uploaded in `.travis.yml`
The build fails with https://travis-ci.org/deepmind/kapitan/builds/575917567 
```
Deploying application
dist/kapitan-linux-amd64 already exists, no checkout
kapitan/__pycache__/__init__.cpython-37.pyc already exists, no checkout
kapitan/__pycache__/version.cpython-37.pyc already exists, no checkout
Could not restore untracked files from stash entry
PyPI upload failed.
failed to deploy
```
For which the dist/ binary stays there because of the `warning: failed to remove dist/kapitan-linux-amd64: Permission denied` error just above in the build error.
The other .pyc artifacts might be another thing that still should be …

Attempt #3 to fix travis pypi deployment, bin/kapitan artifacts are moved to bindist/

---

docs/README.md
docs/contributing.md

Minor documentation update to put info about standalone binary following v0.24 and to clarify a bit more about how to update our gh-pages.
After this, I should submit a PR for gh-pages branch to reflect all the doc updates which have been merged to master (e.g. kubernetes example, helm input examples etc.). If possible, it might be nice in the future to deploy to gh-pages directly from Travis after successful merge to master.

Documentation update for standalone binary and gh-pages update process

---

docs/README.md
docs/contributing.md

My apologies for another minor documentation update.
When contributors want to make a PR for gh-pages, they must do it from a branch that shares commit history with our gh-pages, or Github would throw `There isn't anything to compare` message and prevent PRs to be created. This means we cannot create some new branch using `mkdocs gh-deploy` but should rather commit to a branch that is tracking our gh-pages branch. I added a note on this.

Update instruction for gh-pages deploy

---

kapitan/dependency_manager/base.py
tests/test_dependency_manager.py

Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>
* Adds an additional `Content-Type` header for fetching Tar GZip files over HTTP/S that is commonly set when the response body is not streamed.

Add additional content type header for fetching GZIP files

---

Dockerfile
Dockerfile.ci
Dockerfile.pyinstaller
kapitan/inputs/helm/build.sh
scripts/pyinstaller.sh

Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>
Fixes issue #367
* Updates all Dockerfiles to use multi-stage builds
* Optimized builds while preserving backwards compatibility

Update all Dockerfiles to use multi-stage builds

---

CHANGELOG.md
Dockerfile
Dockerfile.ci

Adds yq to the dockerfiles as it's missing. 
We could also fix Issue #374 in this PR.

Add yq to dockerfile and dockerfile.ci

---

docs/inventory.md
docs/secrets.md
examples/kubernetes/inventory/classes/component/mysql.yml
kapitan/refs/base.py
scripts/kap_5_migrate.py
tests/test_gpg.py
tests/test_refs.py

Fixes issue #277 
- Replace the first occurence of '|' in refs/secrets to '||' for clarity.
This is a __breaking change__ and requires modifying all your refs/secrets.
Before:
`${<ref_type>:<file_path>:<hash_digest>|<func_str|func2|func3>}`
After: 
`${<ref_type>:<file_path>:<hash_digest>||<func_str|func2|func3>}`
Another example:
Before:
`?{gpg:targets/${target_name}/mysql/password|randomstr|base64}`
After:
`?{gpg:targets/${target_name}/mysql/password||randomstr|base64}`

Fix issue #277: Change first '|' operator in secrets functions with '||'

---

docs/compile.md
examples/kubernetes/components/mysql/main.jsonnet
kapitan/lib/kapitan.libjsonnet
kapitan/resources.py
tests/test_jsonnet.py

Introduces new `jsonschema` function in jsonnet.
It can be used to validate the inventory with jsonschema.
Given this inventory:
```yaml
mysql:                   
storage: 10G           
storage_class: standard
image: mysql:latest    
```
The yaml inventory structure can be validated with the new `jsonschema()` function:
```jsonnet
local schema = { type: "object",
properties: {
storage: { type: "string", pattern: "^[0-9]+[MGT]{1}$"},
image: { type: "string" },
}};
// run jsonschema validation
local validation = kap.jsonschema(inv.parameters.mysql, schema);
// assert valid, otherwise error with validation.reason
assert validation.valid: validation.reason;
```
If `validation.valid` is not true, it will then fail compilation and display `validation.reason`.
For example, if defining the …

Jsonschema function for jsonnet

---

kapitan/inputs/helm/__init__.py
kapitan/inputs/helm/go.mod
tests/test_binary.py

Normalise helm compile

---

docs/usage.md
examples/kubernetes/inventory/classes/component/nginx-jsonnet.yml
examples/kubernetes/inventory/classes/component/nginx-kadet.yml
kapitan/cli.py
kapitan/targets.py
tests/test_compile.py
tests/test_jinja2.py

Label selectors for compilation

---

Dockerfile

apt-get ignores recommendations (--no-install-recommends flag) and git recommends ssh-client, so it is not installed, adding ssh-client fixes it.
Reference: https://packages.ubuntu.com/xenial/git

adding ssh-client explicitly as it is only recommended by git

---

docs/compile.md
kapitan/lib/kapitan.libjsonnet
kapitan/resources.py
tests/test_jsonnet.py

Add a new yaml_dump_stream native jsonnet function
Similar to https://github.com/deepmind/kapitan/issues/404 but with dump instead of load.
- Add a new yaml_dump_stream native jsonnet function able to dump a list of json objects into a yaml stream

new yaml_dump_stream() native jsonnet function

---

docs/secrets.md
kapitan/refs/functions.py
tests/test_gpg.py

Fixes issue #302
- Add refs functions to read/write ed25519 keys
- Preserve rsapublic function for backwards compatibility but mark in documentation as "deprecated".

Fix #302, add refs functions to generate/read ed25519 public/private keys

---

docs/compile.md
examples/kubernetes/compiled/busybox/copy/pod.yml
examples/kubernetes/compiled/busybox/pre-deploy/00_namespace.yml
examples/kubernetes/compiled/busybox/pre-deploy/10_serviceaccount.yml
examples/kubernetes/compiled/minikube-es/copy/pod.yml
examples/kubernetes/components/busybox/pod.yml
examples/kubernetes/inventory/classes/component/busybox.yml
examples/kubernetes/inventory/targets/busybox.yml
examples/kubernetes/inventory/targets/minikube-es.yml
kapitan/inputs/copy.py
kapitan/targets.py
tests/test_copy.py
tests/test_kubernetes_compiled/busybox/copy/pod.yml
tests/test_kubernetes_compiled/busybox/pre-deploy/00_namespace.yml
tests/test_kubernetes_compiled/busybox/pre-deploy/10_serviceaccount.yml
tests/test_kubernetes_compiled/minikube-es/copy/pod.yml

- The code provides an input feature of copy
- This feature is to give an opportunity for a plain copy of a component without any alterations. Those can happen by other compiled steps
- The use case come from the fact that the ArgoCD helm plugin requires a helm chart as it is and value files. By default, the directory plugin of Argo do not understand helm hooks. With this feature you can copy the helm chart and render additional value files at convenience.

Copy - input that allows you to get your components plain unaltered to your compile targets

---

CHANGELOG.md

- Fix issue #431: jsonnet compile fails for a single string that isn't an object with items in it. (#432)
- Fix input_paths globbing when search paths are defined (#426)
- Support for ed25519 public/private keys in refs (#422)
- New copy input type (#423)

Start release-v0.26.0

---

Dockerfile.ci

Fixes issue #440
The google-cloud-sdk available in the ci image is not the latest.
Proposal is to upgrade it to the latest Cloud SDK version (274.0.0)

Upgrade to Cloud SDK version (274.0.0)

---

kapitan/cli.py
kapitan/defaults.py
kapitan/inputs/copy.py
kapitan/inputs/jinja2_filters.py
kapitan/inputs/jsonnet.py
kapitan/inputs/kadet.py
kapitan/refs/base.py
kapitan/refs/base64.py
kapitan/refs/functions.py
kapitan/refs/secrets/gpg.py
kapitan/resources.py
kapitan/targets.py
kapitan/utils.py
kapitan/validator/kubernetes_validator.py
tests/test_kubernetes_validator.py

Related to issue #430 
Slightly hard to generalize and add more information (like current filename processed for example)
because references are set/read in multiple places in cli.py as well in various use cases.
It might be feasible to add nicer exception messages there too with the same approach. 
New message looks like this:
```
no backend for ref type: gpsafasg
for key ?{gpsafasg:targets/minikube-mysql/mysql/password||randomstr|base64}
Compile error: failed to compile target: minikube-mysql
```
Which is slightly more helpful but not perfect.

Add key info for RefBackendError for easier debugging

---

kapitan/inputs/base.py
kapitan/inputs/jinja2.py

Fix issue #445: Explicitly create directories for all outputted CompiledFile objects. 

---

kapitan/targets.py

Fixes #454 
cc @ademariag 
```
$ cd examples/terraform
$ kapitan compile
Compiled develop/project1 (0.33s)
Compiled sandbox/project3 (0.50s)
Compiled prod/project2 (0.59s)
```

Display full path of target after compilation

---

docs/CI.md

Fixes issue #476
- Point the website's CI-Dockerfile Link to the Dockerfile.ci in the github repository

Fix dead CI-Dockerfile link by pointing to github

---

examples/kubernetes/compiled/all-glob/manifests/mysql_secret_subvar.yml
examples/kubernetes/refs/targets/all-glob/mysql/subvars
kapitan/cli.py
kapitan/refs/base.py
kapitan/refs/base64.py
kapitan/refs/secrets/awskms.py
kapitan/refs/secrets/gkms.py
kapitan/refs/secrets/gpg.py
kapitan/refs/secrets/vaultkv.py
tests/test_gpg.py
tests/test_kubernetes_compiled/all-glob/manifests/mysql_secret_subvar.yml
tests/test_refs.py

Adds support for embedding content of a ref in the compiled output.
This allows for revealing compiled files without needing access to ref files.
By running `$ kapitan compile --embed-refs`, compiled files with refs will have embedded compiled refs under the following format (gkms as an example): 
`?{gkms:ReallyLongBase64HereZ2FyZ2FiZQo=:embedded}`
Which means that compiled outputs with embedded refs can be completely distributed without the need to access ref contents in their refs directory.
Related to #435
Also fixes issue #499

Compile refs in embedded format

---

kapitan/cli.py
kapitan/targets.py

This fixes the issue where the error logged by kapitan is unclear when using jinja2. 
Because the traceback can be lengthy, I made it listen to the verbose flag for the compile command.
Before:
```
Jinja2 error: failed to render /home/paul/antenna/antenna-ops-kapitan/kubernetes-apps/components/lyst/manifests/django-secret.yaml: 'NoneType' object has no attribute 'encode'
Compile error: failed to compile target: staging
```
After:
```
Jinja2 error: failed to render /home/paul/redacted/redacted-ops-kapitan/kubernetes-apps/components/lyst/manifests/django-secret.yaml: 'NoneType' object has no attribute 'encode'
Compile error: failed to compile target: staging
multiprocessing.pool.RemoteTraceback: 
"""
File …
```

show traceback to explain source of the issue

---

CHANGELOG.md
docs/contributing.md
scripts/pyinstaller.sh

Fix issue #513: add kapitan/inputs/templates to pyinstaller configuration and start release-v0.27.3-rc.3

Fix issue #513: add kapitan/inputs/templates to pyinstaller configuration and start release-v0.27.3-rc.3

---

docs/kap_proposals/kap_7_remote_inventory.md

In the proposal, I mentioned that `.kapitan`can be used to store the remote inventory configuration. From the codebase, I could figure out that `.kapitan` is used to store the arguments of various flags as well. However, after compilation when I list the items (` $ ls -al`) of the root directory  of the project I don't see any `.kapitan` file. Where can I find the `.kapitan` file so that I can manually see its contents?
The command for adding the remote inventories from the cli and fetching it will be:
``` $ kapitan inventory --fetch <output-path> <source> ```
The command for only adding remote inventories to the .kapitan file from cli will be:
```$ kapitan inventory --add <inventory-name> <output-path> <source> ```
The command for fetching all the inventory declared in .kapitan file will …

Remote inventory proposal

---

examples/terraform/inventory/reclass-config.yml
requirements.txt

as well as some pip dependencies.
This reclass update is changing the behaviour of class_mappings matching so if you use that feature add `class_mappings_match_path: true` to your reclass-config.yml to preserve functionality as in this PR.

Update reclass and pip dependencies

---

examples/kubernetes/compiled/busybox/copy/copy_target
examples/kubernetes/compiled/busybox/copy_target
examples/kubernetes/compiled/minikube-es/copy/copy_target
examples/kubernetes/compiled/minikube-es/copy_target
examples/kubernetes/copy_target
examples/kubernetes/inventory/classes/component/busybox.yml
kapitan/inputs/copy.py
tests/test_copy.py
tests/test_kubernetes_compiled/busybox/copy/copy_target
tests/test_kubernetes_compiled/busybox/copy_target
tests/test_kubernetes_compiled/minikube-es/copy/copy_target
tests/test_kubernetes_compiled/minikube-es/copy_target

Added some examples too so they're tested continuously in the future.

Fix issues #535 and #536 by resolving relative paths in the copy input type and not clobbering the output dir

---

Dockerfile
Dockerfile.ci
Dockerfile.pyinstaller

Speed up build time by only building golang binaries when the golang files change, leveraging docker caching.
- Each docker image has the golang binary materials added first and built.

Speed up build time

---

.github/workflows/docker-image.yml
CHANGELOG.md

```
Run docker run -t --rm deepmind/kapitan:master --version
Unable to find image 'deepmind/kapitan:master' locally
docker: Error response from daemon: manifest for deepmind/kapitan:master not found: manifest unknown: manifest unknown.
See 'docker run --help'.
##[error]Process completed with exit code 125.
```
This fixes the master branch edge case where the docker push action translates ("master" <> ref name) to ("latest" <> docker tag).

Fix small bug in github docker action for master branch

---

kapitan/__init__.py
kapitan/cli.py

Fixes issue #558 
Not an ideal fix, but I could not find a better way to fix. Python 3.8 logging on macOS seems to have changed behaviour / or is buggy, as updating logging levels at runtime does not seem to propagate to all loggers.

add logging fix for python 3.8+ on macOS

---

docs/compile.md
kapitan/inputs/kadet.py
kapitan/targets.py
tests/test_compile.py
tests/test_resources/inventory/targets/kadet-test.yml
tests/test_resources/kadet_functions/add_team_label/__init__.py
tests/test_resources/templates/test_deployment.yaml

Adds kadet_params as a way to create compile time parameters for kadet modules. This should enable a reusable plugin like system within a single target, that shows the contract cleary through injection rather than relying on the 'parameters' concept in inventory.
The compile process currently works in a blocking sequential manner. Only targets are multi threaded. This enables a the concept of "post processing" or "overlays" as mentioned in #527 and #365.
- 'kadet_params' as attribute for kadet input type

Adds kadet_params for compile time parameter injection into kadet modules

---

kapitan/resources.py

Enable the reclass `allow_none_override` feature [1] to be able to
remove dicts and lists further down in the hierarchy.
[1] https://github.com/salt-formulas/reclass/blob/develop/README-extensions.rst#allow-override-list-and-dicts-by-empty-entitynone-instead-of-merge
Set `allow_none_override=true` in reclass config.

Allow reclass override none feature

---

docs/kap_proposals/kap_8_modularize_kapitan.md

Utilize pip extras to specify dependencies used with
specific modules such as secret backends.
Related to issue #437

Add proposal to modularize kapitan

---

docs/kap_proposals/kap_8_google_secret_management.md

With [Google Secret Manager](https://cloud.google.com/secret-manager/), Kapitan would be able to share secrets with scripts/processes
that do not have access to the Kapitan repository.
Related to issue #467

Proposal to add support for Google Secret Manager backend

---

kapitan/targets.py

Add a dedicated directory in the `temp_path` to
store the compiled items and finally copy the items
to the compile path.
This way, when `$ kapitan compile --fetch` is used, fetched dependencies won't be copied to the compile path.
Fixes issue #583

Add a dedicated directory in the temp path

---

kapitan/inputs/helm/__init__.py

Fixes issue with dynamically created array of pointers with cffi

---

docs/compile.md
examples/kubernetes/inventory/targets/removal.yml
kapitan/inputs/remove.py
kapitan/targets.py
tests/test_remove.py

- Adds new input type `Remove`. This allows users to remove any compiled files.
- Adds `temp_path` to `search_paths`. This allows users to reference files that have already been compiled for the `Remove` input to work but also opens up the ability to use the outputs of previous compile blocks to be the inputs for preceding compile blocks.

Remove input type

---

docs/compile.md

Fixes issue #594 
doc of jinja2 filters reformatted, codeblock turned into list of items

Reformat list of jinja2 filters in doc

---

docs/secrets.md

Fixes issue #597
- list of secret handling functions reformatted from code block into ordinary list
Pure doc change, no python code touched.

formatted doc for secrets - list of functions

---

kapitan/refs/base.py

currently the reveal of refs for full directory fails if it has json in it with msg,
```
2020-09-21 13:47:50,282 kapitan.refs.base DEBUG    Revealer: revealing json file: compiled/wallet/gcp/terraform/provider.tf.json
2020-09-21 13:47:50,283 kapitan.refs.base DEBUG    Revealer: revealing json file: compiled/wallet/gcp/terraform/provider.tf.json
File "/home/nashaikh/.local/bin/kapitan", line 11, in <module>
sys.exit(main())
File "/home/nashaikh/.local/lib/python3.6/site-packages/kapitan/cli.py", line 561, in main
ref_reveal(args, ref_controller)
File "/home/nashaikh/.local/lib/python3.6/site-packages/kapitan/cli.py", line 798, in ref_reveal
for rev_obj in revealer.reveal_path(file_name):
File "/home/nashaikh/.local/lib/python3.6/site-packages/kapitan/refs/ …
```

fix for reveal of secret for dir with json

---

kapitan/dependency_manager/base.py
tests/test_dependency_manager.py

- Add test for parallel http(s) dependency fetching with unpack=True
- Make temporary directory for unpacking http(s) dependencies unique
We've observed that dependency fetching with the default parallelism setting of 4 and with multiple http(s) dependencies with `unpack=True` sometimes fails with:
```
Unknown (Non-Kapitan) Error occurred
multiprocessing.pool.RemoteTraceback:
"""
File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/path/to/venv/lib/python3.8/site-packages/kapitan/dependency_manager/base.py", line 176, in fetch_http_dependency
os.makedirs(unpack_output)
File "/usr/lib/python3.8/os.py", line 221, in makedirs
mkdir(name, mode)
FileExistsError: [Errno 17] File exists: …
```

Fix FileExistsError when fetching multiple dependencies with unpack=True

---

kapitan/refs/secrets/vaultkv.py

vaultkv `skip_verify` converges on str type to support subsequent `.lower()` string operation for determining `client_parameters["verify"]`.  as `skip_verify` can be sourced from yaml kapitan parameters or an environment variable, it is decidedly simpler to convert any python bool type to string (ie "True" or "False") rather than evaluate truthiness of a mixed bag of bool types and strings.
Fixes issue #622

VAULT_SKIP_VERIFY supports with yaml boolean defined in parameters

---

Dockerfile.pyinstaller
scripts/pyinstaller.sh

Currently the linux binary is not statically linked as pyinstaller does not support this. Patchelf and staticx allow converting a Linux dynamically linked binary into a static binary.

Add staticx and patchelf to pyinstaller.sh to build a Linux static binary

---

requirements.txt

https://github.com/pyca/cryptography/commit/58494b41d6ecb0f56b7c5f05d5f5e3ca0320d494

Bump cryptography to fix CVE-2020-25659

---

requirements.txt

With boto3 1.19.6
```
$ kapitan --version
File "/Users/adrianchifor/Library/Python/3.7/bin/kapitan", line 6, in <module>
from kapitan.cli import main
File "/Users/adrianchifor/Library/Python/3.7/lib/python/site-packages/kapitan/cli.py", line 23, in <module>
from kapitan.refs.cmd_parser import handle_refs_command
File "/Users/adrianchifor/Library/Python/3.7/lib/python/site-packages/kapitan/refs/cmd_parser.py", line 12, in <module>
from kapitan.refs.secrets.awskms import AWSKMSSecret
File "/Users/adrianchifor/Library/Python/3.7/lib/python/site-packages/kapitan/refs/secrets/awskms.py", line 9, in <module>
import boto3
File "/Users/adrianchifor/Library/Python/3.7/lib/python/site-packages/boto3/__init__.py", line 16, in <module>
from boto3.session import …
```

Pin urllib3 to fix kapitan crash on newest boto

---

kapitan/targets.py
kapitan/utils.py

Jsonnet fails on arm / apple M1
```
$ kapitan compile
File "/Users/adrianchifor/Library/Python/3.8/bin/kapitan", line 5, in <module>
from kapitan.cli import main
File "/Users/adrianchifor/Library/Python/3.8/lib/python/site-packages/kapitan/cli.py", line 21, in <module>
from kapitan.lint import start_lint
File "/Users/adrianchifor/Library/Python/3.8/lib/python/site-packages/kapitan/lint.py", line 16, in <module>
from kapitan.utils import list_all_paths
File "/Users/adrianchifor/Library/Python/3.8/lib/python/site-packages/kapitan/utils.py", line 24, in <module>
import _jsonnet as jsonnet
ImportError: dlopen(/Users/adrianchifor/Library/Python/3.8/lib/python/site-packages/_jsonnet.cpython-38-darwin.so, 2): Symbol not found: _jsonnet_destroy
Referenced from: …
```

Note for jsonnet on arm. Skip import if not used

---

kapitan/inputs/kadet.py
kapitan/resources.py
kapitan/targets.py

Compile fails when inventory path is not set in kadet
```
$ kapitan compile
Unknown (Non-Kapitan) Error occurred
multiprocessing.pool.RemoteTraceback: 
"""
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/Users/adrianchifor/code/public/kapitan/kapitan/targets.py", line 453, in compile_target
input_compiler.compile_obj(comp_obj, ext_vars, **kwargs)
File "/Users/adrianchifor/code/public/kapitan/kapitan/inputs/base.py", line 54, in compile_obj
self.compile_input_path(input_path, comp_obj, ext_vars, **kwargs)
File "/Users/adrianchifor/code/public/kapitan/kapitan/inputs/base.py", line 69, in compile_input_path …
```

Fix error for null inventory path in kadet

---

kapitan/inputs/kadet.py

Fixes issue #666 - The number of the beast, hell and fire was spawned to be released

Fix empty kadet output_obj crash

---

docs/compile.md
docs/inventory.md

Summary:
- fix generated documentation formatting for docs/compile.md
- fix typo in docs/inventory.md

Minor documentation fixes

---

docs/compile.md
kapitan/inputs/base.py
kapitan/inputs/copy.py
kapitan/targets.py
tests/test_copy.py

Fixes issue #688
Allows the "copy" input type to continue even if the source path is missing. 
The main motivation behins this change is to enable a workaround to handle terraform lock files which are now being produced when running terraform init, see https://github.com/hashicorp/terraform/issues/27241 
The solution would be to allow adding the following copy settings:
```
kapitan:
compile:
- input_type: copy
ignore_missing: true
input_paths:
- resources/state/${target_name}/.terraform.lock.hcl
output_path: terraform/
```
Without this feature, the compile process would fail for all new environments where the state file has not already been placed in the state folder.

Ignore copy file on missing source

---

kapitan/dependency_manager/helm/go.mod
kapitan/inputs/helm/go.mod

Signed-off-by: Benjamin Hesmans <benjamin.hesmans@tessares.net>
Fixes issue # ??
Did not find any open issue. I tried the build scripts for the binding with go 1.16 and it was not happy
something like
```
/opt/venv/lib/python3.8/site-packages/kapitan/dependency_manager/helm
go: invalid module path ".": is a local import path
```
- add a module name to make it build with go 1.16

Allow helm binding to be compiled with go 1.16

---

kapitan/dependency_manager/base.py
kapitan/initialiser.py
kapitan/inputs/copy.py
kapitan/inputs/external.py
kapitan/inputs/helm/__init__.py
kapitan/inputs/jinja2_filters.py
kapitan/inputs/kadet.py
kapitan/inputs/remove.py
kapitan/lint.py
kapitan/refs/base.py
kapitan/refs/secrets/gpg.py
kapitan/remoteinventory/fetch.py
kapitan/resources.py
kapitan/targets.py
kapitan/utils.py
kapitan/validator/kubernetes_validator.py

Using `format()` for logger is discouraged as it forces the message to format the message even when log are disabled.
Moreover, the `.format` vs `%s` is used inconsistently all over the codebase.
Switching all usages to the logger builtin formatting make the code more consistent.
- convert all usage of `format()` to format logging message to use the builtin logging formatter instead.

Let the logger format the message lazily.

---

kapitan/cli.py
kapitan/resources.py

parser is not defined in generate_inventory
so call to `parser.error("--pattern requires --target_name")` fails.

Fix usage of undefined variable.

---

examples/kubernetes/components/nginx-kadet/__init__.py
kapitan/inputs/kadet.py

There is 2 issues with requiring `BaseObj` in kadet.
kadet Input expects just a mapping of filename -> `dict`. Requiring a `BaseObj` is confusing as it implies kadet expects a single object and not a list of files. This change adds support for raw `dict` as return type. It simplifies implementation of kadet modules as it remove the need to build a `BaseObj` just to returns a mapping of filenames to `BaseObj`.
For instance, the nginx example may be rewrite as:
```python 
def main():
return {
"nginx_deployment": kubelib.Deployment(name=name, labels=labels, containers=[nginx_container]),
"nginx_service": kubelib.Service(name=name, labels=labels, ports=[svc_port], selector=svc_selector)
}
```
instead of 
```python 
def main():
output = kadet.BaseObj()
output.root.nginx_deployment = …
```

Relax kadet output type requirement.

---

Dockerfile.docs
Makefile
docs/contributing.md

Not sure if the process for making documentation changes is still valid, but I dockerized the mkdocs setup since I thought it would be easier to view changes locally before submitting a PR.
- Dockerize mkdocs local preview setup.
- Dockerize documentation publishing.

Dockerizes mkdocs setup.

---

.github/workflows/documentation.yml
Dockerfile.docs
Makefile
docs/contributing.md
requirements.docs.txt

Idea is to update documentation whenever a merge to master occurs. It seems to be easier to use the existing mkdocs Github Action which can deploy the changes without huge configuration changes. I created a new requirements.txt file for documentation python dependencies enabling local and CI changes to use the same libraries.
- update merges to master to automatically update documentation

Update gh pages as a ci job

---

kapitan/utils.py

jinja2.TemplateError does not include the template line number which can be of great help when troubleshooting errors like
'foo' has no attribute 'bar'
The line number can however be inferred from the stack trace. This was inspired by
https://github.com/saltstack/salt/blob/master/salt/utils/templates.py
Example output:
Jsonnet error: failed to compile test/main.jsonnet:
RUNTIME ERROR: Jsonnet jinja2 failed to render templates/abc.j2: Jinja2 TemplateError: 'foo' has no attribute 'bar', at templates/abc.j2:240

improve jinja2 templating error report for TemplateError

---

kapitan/inputs/helm.py

If an input path is found more than once in the search paths.
Then the second compilation will be wrong,
because the helm values were reset after the first compilation.
See: https://github.com/kapicorp/kapitan/blob/master/kapitan/inputs/helm.py#L87-L89
At least raise an exception if this happens.

Raise an error if helm input is compiled twice

---

kapitan/targets.py

Fixes issue #745
- Print time to spent rendering inventory like below
```
Rendered inventory (0.10s)
Compiled removal (0.00s)
Compiled labels (0.10s)
Compiled busybox (0.11s)
...
```

Print inventory render time

---

tests/test_helm_input.py

This change needs to be merged first: https://github.com/kapicorp/reclass/pull/7
* On the latest version, to render helm template it now uses the helm
cli directly. However it seems using helm 3.8.0 (the latest stable),
the default behavior if to release name is specify is to populate with
the string "release-name", not "RELEASE-NAME" hence all lowercase.
There's a simple way to reproduce:
```
helm create test-chart
helm template --include-crds --skip-tests
````
And check how {{ .Release.Name }} gets populated when there's none
specified.
Signed-off-by: Lionel H <me@nullbyte.be>
Fixes issue #
-
-
-

kapitan: fix python tests.

---

kapitan/utils.py

The content-type `application/gzip` has been introduced in [RFC 6713][1]  as an official type which was intendend to be used instead of various custom content types, such as `application/x-gzip`.
It appears that adoption of `application/gzip` is not very high, so its absence from the list of content types which Kapitan tries to unpack hasn't caused issues yet.
However, we've now found a dependency (Cilium Enterprise Edition OLM manifests) which is served with `content-type: application/gzip` which results in the following log messages from Kapitan:
```
Dependency https://<REDACTED>/cilium-ee-1.10.4.tar.gz: fetching now
Dependency https://<REDACTED>/cilium-ee-1.10.4.tar.gz: successfully fetched
Dependency https://<REDACTED>/cilium-ee-1.10.4.tar.gz: Content-Type application/gzip is not …
```

Accept content-type `application/gzip` when unpacking dependencies

---

docs/secrets.md
kapitan/refs/functions.py
tests/test_refs.py

- add lower_alpha_num ref function which generates string without any special characters or capital letters to be compliant with accountName of Azure StorageAccounts - https://docs.microsoft.com/en-us/rest/api/storagerp/storage-accounts/create

feature: add new lower_alpha_num ref function

---

docs/external_dependencies.md
kapitan/dependency_manager/base.py

Since version 3.8.0 Helm supports OCI registries for chart storage [https://helm.sh/docs/topics/registries](https://helm.sh/docs/topics/registries/), but the `helm pull` command used to fetch a chart from an OCI registry slightly changes, the `--repo` flag have to be omitted because it only works with http(s) chart repositories. Helm expects the fully-qualified URL to the chart instead as argument.
This PR adds support for Helm chart dependencies from OCI registries by removing the `--repo` flag passed to the `helm` command when the `oci://` prefix is detected in the `source` property, and pass it as argument instead.
For instance, this configuration:
```yaml
kapitan:
dependencies:
- type: helm
output_path: charts/example
source: …
```

Add support for Helm charts from OCI registries

---

kapitan/cli.py
kapitan/refs/base64.py
kapitan/refs/cmd_parser.py

Fixes #791
The MIME type of files is checked for the "text" keyword. If it is present, the file will be opened in standard text mode (modifier `r`), if not it is assumed to be binary data and opened in binary mode (modifier `rb`).
In case of a binary file, the UTF-8 encoding will be skipped.
Related to https://github.com/kapicorp/kapitan-reference/issues/106

Open binary files in binary mode and do not encode them

---

kapitan/cli.py
tests/test_cli.py

Fixes issue #776, #737
- Caching of args by key should use full command name and not alias
- Inventory alias is duplicated with init alias - changed "i" to "inv"

fix cli alias handling (#776, #737)

---

docs/usage.md
kapitan/cli.py
kapitan/utils.py

**Fixed Issues**
* https://github.com/kapicorp/kapitan/issues/852
* https://github.com/kapicorp/kapitan/issues/843
* https://github.com/kapicorp/kapitan/issues/859
**Added two new CLI-flags:**
1. `--multiline-string-style [STYLE]`
* Set representation of multiline string to given style (default: `"`)
* Available options:
* `literal`: Using `|` as representation (turns every newline within the string into a literal newline)
* `folded`: Using `>` as representation (removes single newlines within the string)
* `double-quotes`: Using `"` as representation (dumps newlines as `\n`-character in one string)
* Find out more about yaml-strings [here](https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines)
2. `--dump-null-as-empty`
* Set representation of …

Feature: Cli-flags for controlling the dumping behavior

---

kapitan/inputs/external.py

Kapitan already substitutes `${compiled_target_dir}` in the command line arguments for the command executed for compile objects with `input_type: external`.
This commit adds logic to also substitue `${compiled_target_dir}` in the environment variables provided to the external command. This allows users to specify the compilation target directory in an environment variable, which can be useful for example to simplify wrapper scripts which do some work before calling the external tool.
See https://github.com/projectsyn/commodore/pull/646 for an example PR which implements a wrapper script for `kustomize`. This wrapper script could benefit greatly from being able to pass the output directory as an environment variable as it would remove the hard requirement of the wrapper script that users …

Substitute `${compiled_target_dir}` in env vars for `input_type: external`

---

docs/compile.md
kapitan/inputs/external.py

For compile objects with `input_type: external`, the external command is executed with `subprocess.run()` with keyword parameter `env`. By providing this keyword parameter, the command will not inherit Kapitan's `os.environ`, as documented in
https://docs.python.org/3/library/subprocess.html:
> If env is not None, it must be a mapping that defines the environment variables for the new process; these are used instead of the default behavior of inheriting the current process’ environment. It is passed directly to Popen.
This commit ensures that we pass `$PATH` and `$HOME` from Kapitan's `os.environ` to the external command unless those environment variables were explicitly set in the compile object's `env_vars`.
- Propagate environment variables `$PATH` and `$HOME` to external command for …

Propagate env vars `$PATH` and `$HOME` for `input_type: external`

---

kapitan/inputs/kadet.py
kapitan/targets.py

Adds a fix to properly raise kadet module loading errors on compile. Prints traceback when exception is not CompileError.
Fixes issue #857

Raise kadet module loading errors

---

docs/external_dependencies.md
docs/inventory.md
docs/kap_proposals/kap_1_external_dependencies.md
docs/kap_proposals/kap_7_remote_inventory.md
docs/usage.md
kapitan/cli.py
kapitan/targets.py
tests/test_remote_inventory.py

Fixes issue: #858 
* Added a option to have a `fetch_always`-property in your external dependencies.
If `fetch_always` is set to `true`, this dependency will always get fetched and overwrite existing files (force-fetch).
* Renamed `--force`-flag to `--force-fetch`, so you have to run
* ` $ kapitan compile --fetch` to fetch (existing files won't get overwritten) or
* ` $ kapitan compile --force-fetch` to fetch the dependencies and overwrite existing files.
If the property is false or not given, the default-behavior of the fetch-functionality doesn't change.
Also the behavior of `--fetch` and (now:)`--force-fetch` doesn't change either.
**NOTE:** Using `--force` will still work with its default behavior, but is now a _deprecated_ flag and will be removed soon.
Updated flag-name in the docs …

Feature: Added force-fetch functionality (#858)

---

docs/inventory.md
docs/secrets.md
kapitan/refs/base.py
kapitan/refs/functions.py
tests/test_refs.py

Fixes issue #694
**New generic `random` function:**
Generates a random string based on given parameters.
```yaml
secret: ?{ref:path/to/secret||random:type:nchars:special}
```
The first parameter `type` has to be one of:
* `str` : generator function for alphanumeric characters, will be url-token-safe
* `int` : generator function for digits (0-9)
* `loweralpha` : generator function for lowercase letters (a-z)
* `upperalpha` : generator function for uppercase letters (A-Z)
* `loweralphanum` : generator function for lowercase letters and numbers (a-z and 0-9)
* `upperalphanum` : generator function for uppercase letters and numbers (A-Z and 0-9)
* `special` : generator function for alphanumeric characters and given special characters
I'm always open for name suggestions.
All these types have …

Added more automatic generator functions (#694)

---

docs/secrets.md
kapitan/refs/functions.py
tests/test_refs.py

- Added a generator function for basic auth secrets
The generator function has two optional arguments: `?{ref:path/to/secret||basicauth:username:password}`
If the arguments are not specified, a text-string containing 8 characters will be generated.
- `||basicauth` could generate something like `dddkfrgl:DDwlFByq` as username:password - token
**NOTE:** The secret itself is base64 encoded so it will look like `ZGRka2ZyZ2w6RER3bEZCeXE=`
- `|basicauth:user123:key123` would exactly generate `user123:key123` as token, so the secret (base64) would be `dXNlcjEyMzprZXkxMjM=`
Added test for basic auth generator function.
Updated `secret.md` as well.

Add basic auth generator function

---

kapitan/targets.py

Fixes issue #868
- Added error handling for empty kapitan.parameters key

Handling error if kapitan.parameters is empty (#868)

---

kapitan/helm_cli.py
kapitan/inputs/helm.py
requirements.txt
tests/test_helm_input.py

Implements support to render helm charts into a kadet object via HelmChart:
```py
>>> from kapitan.inputs.helm import HelmChart
>>> c = HelmChart(chart_dir='tests/test_resources/charts/nginx-ingress', helm_params={'name':'demo'})
>>> list(c.root.keys())
['demo-nginx-ingress-serviceaccount',
'demo-nginx-ingress-clusterrole',
'demo-nginx-ingress-clusterrolebinding',
'demo-nginx-ingress-role',
'demo-nginx-ingress-rolebinding',
'demo-nginx-ingress-controller-service',
'demo-nginx-ingress-default-backend-service',
'demo-nginx-ingress-controller-deployment',
'demo-nginx-ingress-default-backend-deployment']
c.root.demo_nginx_ingress_serviceaccount.root.metadata.name = 'my-new-name'
>>> print(c.root.demo_nginx_ingress_serviceaccount.root)
{'apiVersion': 'v1', 'kind': 'ServiceAccount', …
```

Add HelmChart class to render helm charts as kadet objects

---

kapitan/cli.py

* Add short name `-L` for flag `--yaml-multiline-string-style`
* Reference: https://github.com/kapicorp/kapitan/pull/877#issuecomment-1320969754

Add short name `-L` for flag `--yaml-multiline-string-style`

---

docs/references.md
kapitan/refs/base.py
tests/test_cli.py

Fixes issue #899
* plain references
* references with base64 encoding (it will temporarily decode and re-encode)

Fix subvar for plain 

---

Dockerfile
kapitan/utils.py
requirements.txt

I have the following dependency in kapitan:
```yaml
...
kapitan:
dependencies:
- type: http
output_path: ./freeplane/freeplane.zip
source: https://sourceforge.net/projects/freeplane/files/freeplane%20stable/freeplane_bin-1.10.6.zip/download
unpack: true
...
```
without this patch, the `kapitan compile --fetch` leads to 
```bash
$ kapitan compile --fetch 
Dependency https://sourceforge.net/projects/freeplane/files/freeplane%20stable/freeplane_bin-1.10.6.zip/download: fetching now                        
Dependency https://sourceforge.net/projects/freeplane/files/freeplane%20stable/freeplane_bin-1.10.6.zip/download: successfully fetched                
Dependency https://sourceforge.net/projects/freeplane/files/freeplane%20stable/freeplane_bin-1.10.6.zip/download: Content-Type …
```

more accurate handle for .zip kapitan-dependency

---

kapitan/inputs/jinja2.py
kapitan/targets.py
tests/test_compile.py
tests/test_resources/compiled/jinja2-postfix-strip/stripped-overridden/stub
tests/test_resources/compiled/jinja2-postfix-strip/stripped/stub.txt
tests/test_resources/compiled/jinja2-postfix-strip/unstripped/stub.txt.j2
tests/test_resources/inventory/targets/jinja2-postfix-strip.yml
tests/test_resources/templates/stub.txt.j2

Added options "strip_postfix" and "stripped_postfix" to jinja2 input. This allows to remove output files extensions which is often the case for jinja2 template files (.j2).
Stripping is disabled by default and default value to strip is ".j2".
Closes issue #805
- add option "strip_postfix" to jinja2 input
- add option "stripped_postfix" to jinja2 input
- optional removal of file postfixes (i.e. extensions) on output files

feat/strip-j2-jinja: implement rstrip for jinja2 input

---

kapitan/inputs/base.py
kapitan/inputs/jsonnet.py
kapitan/inputs/kadet.py
kapitan/targets.py
tests/test_compile.py
tests/test_resources/compiled/toml-output/jsonnet-output/nested.toml
tests/test_resources/compiled/toml-output/kadet-output/nested.toml
tests/test_resources/components/input-to-output/main.jsonnet
tests/test_resources/inventory/targets/toml-output.yml
tests/test_resources/kadet_functions/input_to_output/__init__.py

TOML output format has been added to jsonnet and kadet inputs, along with tests for verification.
Partially covers issue #256 
- support for toml output in jsonnet input
- support for toml output in kadet input

feat/#256/toml-output-format: implement toml output format

---

kapitan/inputs/jinja2.py
kapitan/inputs/kadet.py
kapitan/targets.py
tests/test_resources/inventory/targets/jinja2-input-params.yml

Fixes issue #906
- do not reset input_params in between compile
- clean up the way input_params are passed to Kadet and Jinja
- also exposes compiled path to jinja (same as Kadet)
- adds test
```
kapitan compile -t jinja2-input-params
Rendered inventory (0.04s)
Jinja2 error: failed to render /usr/local/google/home/ademaria/isolabs/kapitan/tests/test_resources/templates/pod.yml: Jinja2 TemplateError: 'dict object' has no attribute 'name', at /usr/local/google/home/ademaria/isolabs/kapitan/tests/test_resources/templates/pod.yml:4
Compile error: failed to compile target: jinja2-input-params
```
```
kapitan compile -t jinja2-input-params
Rendered inventory (0.04s)
Compiled jinja2-input-params (0.01s)
```

fix #906: Jinja input_params gets reset

---

kapitan/initialiser.py

Former implementation showed all files in target directory and skipped some of generated files. Now only files generated are shown and formatting has been changed to more tree [1] like - from [2] to [3]
Closes #306
[1] https://linux.die.net/man/1/tree
[2]
```
Populated /tmp/fake with:
/tmp/fake
/tmp/fake/templates
/tmp/fake/templates/docs
my_readme.md
/tmp/fake/components
/tmp/fake/components/other_component
__init__.py
```
[3]
```
Populated /tmp/fake with:
inventory
classes
common.yml
my_component.yml
targets
my_target.yml
templates
scripts
my_script.sh
docs
my_readme.md
components
my_component
my_component.jsonnet
other_component
__init__.py
```
fixes ae0b44486c2c

fix/non-kapitan-files-on-init-list: refactor populated files listing

---

kapitan/inputs/external.py

I've noticed that the current implementation for propagating the environment variables `$HOME` and `$PATH` to the subprocess spawned for the external input type can raise an error if either or both of the variables aren't present in Kapitan's environment.
When one of the variables was missing, the original implementation would propagate value `None` to the subprocess, which causes a `TypeError` when trying to spawn the subprocess:
```
Unknown (Non-Kapitan) error occurred:
multiprocessing.pool.RemoteTraceback:
"""
File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/home/simon/work/syn/commodore/.tox/py38/lib/python3.8/site-packages/kapitan/targets.py", line 500, in compile_target …
```

Only propagate env vars which are present for input type `external`

---

docs/README.md

necessary for https://pypi.org/project/python-magic/, which is a sub-dependency. See link.

Add libmagic to mac install

---

README.md
docs/README.md

* Because the `pip.lock` file was deleted the version badge in the readme did not work anymore
* New badge fetches version from PyPi directly
* ![version badge](https://img.shields.io/pypi/pyversions/kapitan)

Fix python version badge

---

.github/workflows/docker-image.yml
Dockerfile
README.md

Fixes issue #939
On a M1 / M2 mac the performance are 5x worse for our use case if using the amd64 docker.
We would like to have the possibility of using a multi-plateform image, and this PR allows that : 
- Update the Dockerfile to use the TARGETARCH environment variable to pull the correct version of go.
- Update the docker-image github action pipeline to setup QEMU and buildx, 
and then building multi-plateform images of kapitan.
Building an image on a computer of the same architecture should work as previously. 
I could add some documentation on how to do locally what the CI does (build a multi-arch image with a single tag).
This was inspired by this bit of documentation about building multi-plateform images : https://docs.docker.com/build/ci/github-actions/examples/#multi-platform-ima …

Build multi-arch docker images

---

.github/workflows/test.yml
.pre-commit-config.yaml
Dockerfile
poetry.lock
pyproject.toml

Fixes issue #965
Update Poetry, Pre-commit, Github Action and Docker image to use Python 3.8.

chore: remove support for Python 3.7

---

kapitan/inputs/base.py
kapitan/inputs/jsonnet.py
kapitan/inputs/kadet.py

Fixes issue with kadet pruning
```
kapitan:
compile:
- output_path: manifests
input_type: kadet
output_type: yml
prune: false   <------- honour this prune to override the default
```
- a typo was preventing "prune" to be read from the input definition ([see](https://github.com/kapicorp/kapitan/blob/f5fd147682e7e47943e2330942d7610960fec642/kapitan/inputs/base.py#LL81C23-L81C23))

Fix typo in kadet prune input handling

---

kapitan/resources.py

Fixes issue #969 
- Refactor, fix and simplify the parsing / reading process of `reclass-config.yml` file
- It's unclear if the attribute `inventory_base_uri` is relative to its location (`inventory_path`) and if the subdirs `targets` (`nodes_uri`) and `classes` (`classes_uri`) should get their path from the `inventory_path` or the `inventory_base_uri`. I implemented it the way it was before ( --> `inventory_path`) but i would be nice to change that.
- We could add some documentation about this config file, especially with the new `compose-node-name` feature in #933 
---

Fix reclass config-file reading

---

.github/workflows/python-black.yml
.github/workflows/test.yml

- github actions don't run twice in a pull-request, because of triggers `push` and `pull-request`
@kapicorp/kapicorp What are your thoughts on running the tests in a os matrix, like for Windows, MacOS and Linux?
---

fix(gh-actions): Avoid running pipeline twice for pull-requests

---

kapitan/inputs/kadet.py
mkdocs.yml

- Fix the tests, which were failing because of merge information introduced by #993
- I noticed that [https://kapitan.dev/inventory/introduction.md](https://kapitan.dev/inventory/introduction.md) gives an 404 error, so I updated the path in `mkdocs.yaml`
---

fix(tests): remove merge annotations from #993

---

docs/pages/external_dependencies.md
kapitan/dependency_manager/base.py
kapitan/remoteinventory/fetch.py
kapitan/utils.py

Fixes issue #
Improve logging for remote fetch to make it less verbose and noisy. Aim is to allow for it to be enabled by default.
- fix logging 
- improve documentation
```
compile:
fetch: true
```
```
$ rm -fr components/generators/kubernetes/
```
```
$ kap compile
creating components/generators/kubernetes
Dependency https://github.com/kapicorp/kapitan-reference.git: saved to components/generators/kubernetes
Rendered inventory (3.76s)
Compiled pritunl (0.10s)
Compiled vault (0.09s)
Compiled examples (0.13s)
Compiled gke-pvm-killer (0.05s)
Compiled mysql (0.05s)
Compiled postgres-proxy (0.06s)
Compiled echo-server (0.06s)
Compiled sock-shop (0.16s)
Compiled global (0.04s)
Compiled tutorial (0.07s)
Compiled guestbook-argocd (0.05s)
Compiled kapicorp-project-123 (0.04s)
Compiled …
```

Improve remote fetch logging

---

tests/test_vault.py
tests/test_vault_transit.py

Fixes tests
- Hashicorp changed their tags for the `vault` image to `hashicorp/vault`
---

fix(tests): set vault image to new `hashicorp/vault` tag

---

.github/workflows/documentation.yml

Fixes issue #
- Simplify workflow
- Add paths
- upgrade actions

Improved documentation workflow

---

.github/workflows/test-build-publish.yml

fix vars instead of env being used

---

.github/workflows/test-build-publish.yml

- runs tests only once (coverage already runs the tests)
-
-

speed up python tests by running them only once

---

.github/workflows/housekeeping.yml

Fixes #902
- Added a github-action that marks issues as stale and closes them, if they not get any activity.
- Parameters:
- schedule: daily at 00:00
- mark issues as stale: 90 days
- close stale issues: 7 days
- mark pr's as stale/ close pr: never
---

chore(gh-actions): Add housekeeping action to close stale issues

---

Dockerfile

As specified by the golang [release policy](https://go.dev/doc/devel/release#policy), "each major go release is supported until there are two newer major releases", which mean that the oldest supported version is currently go 1.20. 
I propose we upgrade the golang version used in the Dockerfile to build go-jsonnet to go 1.20.7 (but we could switch to go 1.21.0 as well if preferred).

chore: bump Dockerfile golang version to 1.20

---

.github/workflows/test-build-publish.yml

* Fixes the following issue: 
On default-branches (or test/*) on forks with no docker-username, the docker buildx command fails, because no name is given and the images are named `/kapitan[...]`, which is not allowed and throws `invalid reference format`. Now if no name is given, the command will be skipped.
[Action run on nexenio-fork for reference](https://github.com/neXenio/kapitan/actions/runs/6378617783/job/17310272281)

fix(gh-actions): only publish when name is given

---

.github/workflows/housekeeping.yml

* mark issues as stale after 1 year
* don't close any issues
* enhance bot message

fix: reconfigure housekeeping action

---

kapitan/refs/vault_resources.py
kapitan/utils.py

Fixes #1078 
* import libmagic only when it is needed

fix: import libmagic only when its needed

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/workflows/test-build-publish.yml
Dockerfile
poetry.lock
pyproject.toml

Fixes #
* Update python base image to 3.11

Update python test versions and python image to 3.11

---

.gitmodules
Dockerfile
poetry.lock
pyproject.toml

Revert "Install reclass as pip package"

---

.github/workflows/test-build-publish.yml

Reverts kapicorp/kapitan#1107
`v2` does not support `suffixes` anymore and goes with a new `sources` approach, where you would define the links to the image via digest. Wit hour current matrix strategy its hard to retrieve the digest per image / per platform. So let's rollback for now!
Guide to migrate by action owner:
This action no longer supports the `suffixes` input.
You need to set an image URI with a digest or tag.
If you use docker/build-push-action, you can construct an image URI from the outputs as follows:
```yaml
- uses: docker/build-push-action@v5
id: build-amd64
with: # ...omit...
- uses: docker/build-push-action@v5
id: build-arm64
with: # ...omit...
- uses: int128/docker-manifest-create-action@v2
with:
tags: ghcr.io/${{ github.repository }}:main
sources: |
ghcr.io/${{ …
```

Revert "chore: bump int128/docker-manifest-create-action from 1 to 2"

---

kapitan/inventory/inv_reclass.py

There's no need to reconstruct the list of classes for each target. Reclass provides this information in `rendered_target["classes"]` already.
This commit removes the loop which reconstructs the list and replaces it by assigning `rendered_target["classes"]` to the target's `classes` field.
Side-note: the previous implementation also mangled the list, because Python implements `+=` for lists as list concatenation, and (not so helpfully) treats strings as lists of characters when they appear in a context where a list is expected. To correctly construct the list of classes with the previous approach, the `+=` should be replaced with append:
```python
self.targets[target_name].classes.append(class_name)
```

Simplify populating each target's classes list in `ReclassInventory`

---

docs/pages/commands/kapitan_dotfile.md
kapitan/utils.py
tests/test_from_dot_kapitan.py

* Introduce section `global` in the `.kapitan` config file as discussed in #1127

Add support for `global` section in `.kapitan`

---

docs/pages/commands/kapitan_compile.md
docs/pages/commands/kapitan_dotfile.md
kapitan/cli.py
kapitan/inventory/__init__.py
kapitan/resources.py
kapitan/utils.py
tests/test_from_dot_kapitan.py

This PR switches the inventory backend command line flag to the form `--inventory-backend=<backend name>`. Additionally, we restrict the allowed values for the flag to the known backends.
To ensure the allowed values for the command line flag, and the known implementations are in sync, we introduce a dict holding the mapping from flag values to `Inventory` subclasses.
Finally, we ensure that the selected backend is cached as a string in `cached.args["inventory-backend"]`. Note that this is not how `cached.args` is used otherwise, but since it's unlikely that there ever will be a real command `inventory-backend` this should be fine.

Refactor handling of inventory backend command line flag

---

docs/pages/kapitan_overview.md
mkdocs.yml

fix docs deployment

---

kapitan/inventory/inventory.py

Only render Reclass inventory if `render_targets()` is called with either `targets=None` or a non-empty list of targets to render. Without this, the whole Reclass inventory is rendered for pretty much every call to `get_targets()` since that method calls `render_targets()` with `targets=[]` if it already has parameters for all targets.

Don't call `render_targets()` from `get_targets()` when all requested targets are cached

---

Dockerfile

As specified by the golang [release policy](https://go.dev/doc/devel/release#policy), "each major go release is supported until there are two newer major releases", which mean that the oldest supported version is currently go 1.21.

chore: bump Dockerfile golang version to 1.21

---

examples/kubernetes/compiled/jsonnet-env/jsonnet-env/env.yml
examples/kubernetes/components/jsonnet-env/env.jsonnet
examples/kubernetes/inventory/classes/jsonnet-env.yml
examples/kubernetes/inventory/targets/jsonnet-env.yml
kapitan/inventory/inv_reclass.py
kapitan/inventory/inventory.py
kapitan/resources.py
tests/test_compile.py
tests/test_kubernetes_compiled/jsonnet-env/jsonnet-env/env.yml

* Restore the Kapitan <= 0.32 behavior of exposing the Reclass `applications`  (which Commodore depends on) and `exports` fields in the inventory

Expose `applications` and `exports` fields in `InventoryTarget` and Jsonnet `inventory()` callback

---

kapitan/inventory/inv_reclass_rs.py
kapitan/inventory/inventory.py
tests/test_compile.py

This is a follow-up for #1059 and #1142. We forgot to include the fix in #1142 in #1059.
* Fix incorrect default initializer for `exports` field of target
* Set `applications` and `exports` in reclass-rs backend
* Run Kubernetes compile tests with reclass-rs

Add missing initialization for `applications` and `exports` in reclass-rs backend

---

.github/workflows/test-build-publish.yml
Dockerfile
kapitan/cached.py
kapitan/cli.py
kapitan/inputs/base.py
kapitan/inputs/jinja2_filters.py
kapitan/inputs/kadet.py
kapitan/inventory/inv_reclass.py
kapitan/inventory/inventory.py
kapitan/resources.py
kapitan/targets.py
kapitan/utils.py
poetry.lock
pyproject.toml
tests/test_compile.py
tests/test_compose_node_name.py
tests/test_inventory.py
tests/test_jinja2.py
tests/test_resources/inventory/targets/test-objects.yml
tests/vault_server.py

Incremental changes from https://github.com/kapicorp/kapitan/pull/1173
* Incremental changes from https://github.com/kapicorp/kapitan/pull/1173
* Move to Pytest

Incremental changes from OmegaConf work #1173

---

kapitan/dependency_manager/base.py
kapitan/initialiser.py
kapitan/inputs/copy.py
kapitan/inputs/external.py
kapitan/inputs/remove.py
kapitan/utils.py
tests/test_remote_inventory.py

Fixes #963.
Whereas #964 just attempted to replace copy_tree, this replaces all the remaining references to distutils. This ought to make it possible to proceed with #1119 and add Python 3.12 to the test set.

Completely remove any references to distutils

---

kapitan/cli.py
tests/test_compile.py
tests/test_resources/inventory/targets/reveal-output.yml

* Add a `--no-reveal` flag to compile command to avoid revealing secret (useful if a `reveal: true` is set in the `.kapitan` config file) 
* [] Updated documentation

feat:  Add a --no-reveal flag in compile command to avoid revealing refs

---

kapitan/cli.py
kapitan/inventory/inv_reclass.py
kapitan/inventory/inv_reclass_rs.py
kapitan/inventory/inventory.py
kapitan/resources.py
tests/test_inventory.py

This is a couple of fixes for an issue we encountered when testing the current version on `master` against our inventories, which use `inventory_global`. This also adds a missing arg for the `kapitan inventory` command that I encountered while debugging the global inventory issue. I've also included a few changes to the types to make things a little clearer for other contributors and Pylance/IDE type checking.
`black` seems to have made quite a few formatting changes during pre-commit, which I'm happy to back out if we don't want those!
* Add `--yaml-dump-null-as-empty` flag to `kapitan inventory` (required by the YAML dumper)
* Ensure the global inventory is returned to Jsonnet as a Python dict instead of a Pydantic type

Fixes for Jsonnet global inventory and inventory dumping

---

kapitan/inventory/inventory.py

This PR adjusts the type annotation and initialization for `InventoryTarget.exports` to be a `dict` which is the correct type for the reclass `exports` field.
Without this, Kapitan logs the following warning multiple times when running `poetry run make test`:
```
/home/simon/.cache/pypoetry/virtualenvs/kapitan-f1_prbYm-py3.10/lib/python3.10/site-packages/pydantic/main.py:314: UserWarning: Pydantic serializer warnings:
Expected `list[any]` but got `dict` - serialized value may not be as expected
return self.__pydantic_serializer__.to_python(
```

Correctly specify `InventoryTarget.exports` field as a `dict`

---

.github/workflows/test-build-publish.yml

Fixes #
* automatically sets "latest" tag to the latest semver match
* see https://github.com/docker/metadata-action?tab=readme-ov-file#flavor-input

set latest to higher semver

---

Dockerfile
examples/kubernetes/compiled/jsonnet-env/jsonnet-env/env.yml
examples/kubernetes/components/jsonnet-env/env.jsonnet
examples/kubernetes/inventory/targets/jsonnet-env.yml
kapitan/cached.py
kapitan/cli.py
kapitan/inputs/base.py
kapitan/inputs/jinja2.py
kapitan/inputs/kadet.py
kapitan/inventory/__init__.py
kapitan/inventory/inv_omegaconf/inv_omegaconf.py
kapitan/inventory/inv_omegaconf/migrate.py
kapitan/inventory/inv_omegaconf/resolvers.py
kapitan/inventory/inv_reclass.py
kapitan/inventory/inv_reclass_rs.py
kapitan/inventory/inventory.py
kapitan/resources.py
kapitan/targets.py
kapitan/version.py
overrides/main.html
poetry.lock
pyproject.toml
tests/test_compile.py
tests/test_inventory.py
tests/test_kubernetes_compiled/jsonnet-env/jsonnet-env/env.yml
tests/test_omegaconf.py

* Implements [OmegaConf](https://github.com/omry/omegaconf) based Inventory by @MatteoVoges (@kapicorp/nexenio-team)
* Speeds up inventory loading and compilation (2x faster)
```
global:
compose-target-name: true
inventory-backend: omegaconf
```
or use the command line flag `--inventory-backend=omegaconf`
```
Migrate your inventory
./kapitan compile --migrate
```

feat: omegaconf inventory by @MatteoVoges

---

.github/workflows/documentation.yml
mkdocs.yml

Switch to use mike for deploying docs 

---

.github/workflows/documentation.yml
.github/workflows/test-build-publish.yml
Dockerfile.docs
Makefile
docs/pages/contribute/documentation.md
poetry.lock
pyproject.toml
requirements.docs.txt

fix: move docs requirements to poetry

---

kapitan/dependency_manager/base.py
kapitan/utils.py
poetry.lock
tests/test_utils.py

When force fetching Git dependencies, we need to be able to overwrite read-only files in the destination, since Git repos may contain read-only pack and index files in `.git/`.
To do so, this PR introduces flag `clobber_files` for `utils.copy_tree()` which will completely clobber existing files in the
destination by setting a custom `copy_function` for `shutil.copytree()` which deletes existing destination files before copying them with `shutil.copy2()`.
With this change, `utils.copy_tree()` with `clobber_files=True` behaves pretty much identically to distutils' `copy_tree()` which was used in previous versions of Kapitan.

Fix `fetch_git_dependency()` to clobber files in the destination if `force_fetch=True`

---

kapitan/inventory/model/dependencies.py

Move the optional `force_fetch` field to the `KapitanDependencyBaseConfig` type.
We access the `force_fetch` field without regard to the dependency type in https://github.com/kapicorp/kapitan/blob/593e5f90888fcd48bed2477f1f22407187e1845b/kapitan/targets.py#L118

Add optional `force_fetch` field for all dependency types

---

Dockerfile

As go 1.21 is end of life, upgrade go to 1.23.2 version in Dockerfile.

Upgrade go to 1.23.2 in Dockerfile

---

kapitan/inventory/model/input_types.py

Fixes #1257
* `KapitanInputTypeKadetConfig.prune` defaults to `False` instead of `True` (inherited).
* Type hint for `KapitanInputTypeJsonnetConfig.prune` is consistent with `KapitanInputTypeBaseConfig.prune`.

#1257 Kapitan does not prune Kadet input

---

examples/kubernetes/inventory/classes/component/nginx-helm.yml
kapitan/inputs/helm.py
kapitan/inventory/model/input_types.py

Fixes #
* Forces the helm input_type to autodetect extension

Forces HELM to use auto settings as output_type

---

poetry.lock
pyproject.toml

Fixes https://github.com/projectsyn/reclass-rs/issues/148 -- reclass-rs didn't discover targets in subdirectories of `inventory/targets` without compose-node-name (e.g. when compiling the kapitan-reference repo).
* Update reclass-rs to `^0.6.0`

Update reclass-rs to ^0.6.0

---

.github/ISSUE_TEMPLATE/bug_report.yml

Previously, the label of the `python-version` field was also "Version (kapitan)".

Correct label for python version in bug report template

---

Dockerfile

In our project using kapitan, we have poor go-jsonnet performance. After some investigation, I think it could be linked to the go version used to build it. For example, on my M1 Pro machine, the build time decreased from 53 seconds to 24 seconds when upgrading from Go 1.23.2 to 1.23.8.
<details>
<summary>Detailed Benchmark Results</summary>
```
Testing 1.23.2
Rendered inventory (9.43s): discovered 9 targets.
Compiling 9/9 targets using 8 concurrent processes: (8 CPU detected)
[...]
Compiled 9 targets in 50.32s
[...]    0.02s user 0.02s system 0% cpu 1:01.93 total
Testing 1.23.3
Rendered inventory (9.69s): discovered 9 targets.
Compiling 9/9 targets using 8 concurrent processes: (8 CPU detected)
[...]
Compiled 9 targets in 46.50s
[...]    0.02s user 0.02s system 0% cpu 59.375 total
Testing …
```

Upgrade go version used in Dockerfile to 1.24.2

---

kapitan/resources.py

Reduce duplicate error messages from inventory errors. Each of the backends already print out the errors. example:
https://github.com/kapicorp/kapitan/blob/master/kapitan/inventory/backends/reclass/__init__.py#L59
Also changed exit point for kapitan inventory errors
better to exit at `get_inventory` instead of `generate_inventory`.
- "kapitan inventory" calls generate_inventory which then calls get_inventory
- "kapitan compile" calls get_inventory
Best to exit at the function that's common for both
kapitan/examples/kubernetes/inventory/targets/labels.yml
```
classes:
- common
- component.namespace
- component.labels
parameters:
target_name: labels
key: ${invalid}               # INVALID REFERENCE
```
```
kapitan inventory --inventory-backend=reclass
Inventory reclass error: -> labels …
```

remove duplicate inventory error

---

pyproject.toml

Follow-up for #1338 where I forgot to update the `classifiers` list in `pyproject.toml` with an entry for Python 3.13

Add missing classifier for Python 3.13
